### ISSUE TITLE
Uploading png, jpeg or pdf fails in pull request comments

### ISSUE THREAD

**Issue by JuergenSimon** [agileseason/agileseason-v1#1014]
When trying to upload any files to a PR comment, I get an error: 

"We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

This is also the case here, therefore I can't upload them. Not even as ZIP files. Using Chrome (Version 55.0.2883.75 (64-bit)) on macOS Sierra (10.12.1 (16B2659))

**Comment by blackchestnut** [comment]
Hi, @JuergenSimon
Agile Season currently supports only images.
If you try to attach a zip file you will see en error message: `Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG`.
If you want to attach other files, you can do it directly via GitHub.
