### ISSUE TITLE
Design question - menu/settings

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#103]
@Sfolt хотел узнать твое мнение по нескольким вопросам (см. комментарии)

**Comment by blackchestnut** [comment]
@Sfolt куда можно сунуть настройки борда?
![agile season 2015-01-22 08-55-13](https://cloud.githubusercontent.com/assets/2400100/5851204/9f058f34-a214-11e4-840a-dfdf74ab675c.png)

**Comment by blackchestnut** [comment]
@Sfolt какой тебе больше всего нравиться вариант отображения notice? Gihub, Gitlab, Uptimus, может еще какие-нибудь варианты?
![agile season 2015-01-22 08-59-20](https://cloud.githubusercontent.com/assets/2400100/5851244/329c8d4c-a215-11e4-9365-e3bd076d6233.png)

**Comment by DariaUlanova** [comment]
@blackchestnut 

> куда можно сунуть настройки борда?

Либо как на скриншоте, либо сразу после названия борда «Agile Season kanban board *». В обоих случаях иконка относится к борду.

> какой тебе больше всего нравиться вариант отображения notice? Gihub, Gitlab, Uptimus, может еще какие-нибудь варианты?

Оформление любых элементов интерфейса по-началу можно брать из гитхаба, чтобы долго не думать.

**Comment by blackchestnut** [comment]
Ок.
