### ISSUE TITLE
Как обновляются issue?

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#109]

**Comment by DariaUlanova** [comment]
@blackchestnut 

Из [документации](https://developer.github.com/v3/issues/#edit-an-issue) поняла, для обновления тикета нужно
1. сформировать данные для отправки — что у тикета хотим обновить;
2. указаь урл в репозирорий гитхаба `/repos/:owner/:repo/issues/:number`;
3. указать метод передачи данных, например, `PATCH`.
Првильно ли я поняла?

В твоем коде в `services/github_api/issues.rb` есть обновление тикетов в методах `move_to` , `archive` и нигде нет ничего подобного из документации про обновление. В этих методах ты используешь `client.update_issue()`. Откуда берется метод `update_issue()`?

**Comment by blackchestnut** [comment]
@Sfolt вот от сюда https://github.com/octokit/octokit.rb, в проекте этот гем подключен. Посмотри исходники, например тут https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/issues.rb есть правда некоторые моменты мне не всегда понятны с тем, что не все методы работают как нужно, но это как правило исключение.

**Comment by DariaUlanova** [comment]
Ok, понятно
