### ISSUE TITLE
Issue's body doesn't appear when the issue is created in github. For example #109

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#110]

**Comment by DariaUlanova** [comment]
It seems to me the issue's body has been overwriting in method `move_to` when it was moving to another column.

**Comment by blackchestnut** [comment]
@Sfolt это вопспроизводится на agileseason.com? Часть ошибок фиксил тут - Missing body after move issue!#86

**Comment by blackchestnut** [comment]
@Sfolt ага, бага есть, исправлю в - Move trackstats from comments to issuestat#101
