### ISSUE TITLE
Зачем нужно было переименовывать из *.css.sass в *.sass?

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#122]
В этом коммите https://github.com/agileseason/agileseason/commit/5adb9ac6a4f0f7250ca0ed1bd13fb37ac6fbf27f

**Comment by blackchestnut** [comment]
после обновления рельсы стали писать предупреждения на каждый прогон тестов по контролерам.

**Comment by DariaUlanova** [comment]
@blackchestnut У меня тоже rspec ругался, но не на все, а только на миксины и файл с саас переменными, и вим ещё себя странно вел. В моей ветке все стили с расширением *.css.sass кроме миксинов и variables.sass. Я могу так запушить, или переделать все в *.sass?

**Comment by blackchestnut** [comment]
у тебя проблема с .css.sass или с .sass? vim на сохранении каких-то файлов по-моему то же предупреждение выдавал, сейчас не могу проверить т.к. с телефона. посмотри пожалуйста если у тебя не ругается на обычные файлики со стилями, то возможно я погорячился и можно вернуть там где не ругается.

**Comment by DariaUlanova** [comment]
@blackchestnut у меня вим начал ругаться когда я подлила изменения этого коммита, я сначала не заметила, что все стили стали в формате *.sass, потом каким-то образом у меня возникли дублирующиеся файлы стилей обоих форматов *.css.sass и *.sass. Я удалила дубляжи и всё переименовала в *.css.sass.Потом rspec начал ругаться на миксины и variables.css.sass, их мне пришлось переименовать в *.sass и тогда rspec успокоился.
