### ISSUE TITLE
Create backlog for MVP.1

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#123]
# Agile season MVP.1
## Тикеты

Подключить Markdowm editor для описания и комментариев 
Сортировка тикетов  драг-н-дропом
Убрать в действиях перезагрузку страницы на борде, заменить аяксом, чтобы все быстро отображалось.
Назначение, переназначение людей в попапе
Удаление комментария в попапе
Добавление изображения или файла в попапе (миниатюра со ссылкой на картинку в исходном размере, которая откроется в соседней вкладке или ссылка на скачивание файла). Иконка файла в миниатюре или картинка.
добавить дату дедлайна в попапе, отображение иконки в миниатюре
Ссылка на тикет
## Колонки

Добавление колонки из борда
Переименование колонки
Удаление колонки
Сортировка колонок драг-н-дропом
Убрать лишние теги для колонок
## Логи

Как в трелло панель справа с логами пользователей.

Краткое описание фич на лендинге

Быстрый фильтр по назначенному (визуально либо остальные тикеты исчезают, либо сереют)

**Comment by blackchestnut** [comment]
Нужно определиться с функционалом, который необходим до начала рекламной деятельности и тестирования на реальных пользователях.

**Comment by DariaUlanova** [comment]
@blackchestnut, когда ты планируешь рекламировать и как?

**Comment by DariaUlanova** [comment]
@blackchestnut, добавила описание наверху к этому тикету.

Дополни, пожалуйста, если я что-то упустила.

Часть можно определить в MVP.2, что, на твой взгляд, можно?

Если удобнее будет обсуждать в ГД, [ссылна на документ](https://docs.google.com/document/d/1EWt0QvjviIlalu_o70jXsr0DR5eUbrq9QpfYhhzrVNs/edit?usp=sharing).

**Comment by blackchestnut** [comment]
@Sfolt здорово, давай обсуждать в ГД - там комментарии удобней делать.

**Comment by blackchestnut** [comment]
@Sfolt добавь, в Backlog что тебе кажется интересным и что я забыл. Пока получается по истории закрытых тикетов у нас с тобой уйдет на это около 200 дней :)

**Comment by blackchestnut** [comment]
@Sfolt добавь, в Backlog что тебе кажется интересным и что я забыл. Пока получается по истории закрытых тикетов у нас с тобой уйдет на это около 200 дней :)

**Comment by DariaUlanova** [comment]
Меньше года!

**Comment by blackchestnut** [comment]
Ага :) ну я надеюсь сейчас подразгребу свои дела да и закончу с описанием, которое у меня что-то затянулось - тогда думаю быстрее пойдет.
![agile season 2015-02-11 21-36-04](https://cloud.githubusercontent.com/assets/2400100/6153486/0630567c-b236-11e4-93e6-29893d50f341.png)
