### ISSUE TITLE
Are labels required for columns?

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#124]
@Sfolt после рефакторинга появилась возможность избавиться от ярлыков в гитхабе для колонок. Они стали напрягать, т.к. гитхаб с недавнего времени легирует все изменения по тикету. Их отсутствие также упростит возможный функционал по переименованию, добавлению и сортировки столбцов. И плюшка возможности фильтрации в самом гитхабе по колонкам-ярлыкам возможно надумана мной.

**Comment by blackchestnut** [comment]
Что думаешь по этому поводу?

**Comment by DariaUlanova** [comment]
@blackchestnut я за то, чтобы убрать ярлыки типа «[3] In Progress», мешать столбцы с ярлыками не логично и не удобно.

**Comment by blackchestnut** [comment]
хорошо, тогда в топку их #126 .
