### ISSUE TITLE
Bad markup of dropdown with boards

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#140]

**Comment by blackchestnut** [comment]
@Sfolt It's actual now?

**Comment by blackchestnut** [comment]
@Sfolt It's actual now?

**Comment by DariaUlanova** [comment]
@blackchestnut Yes it is. I have not created my board in agileseason.com yet just having only your already created board that is why my dropdown drops empty. It is bug. Moreover I have not fix its markup yet.

**Comment by blackchestnut** [comment]
duplicate #283
