### ISSUE TITLE
Design Board#show v.0.1

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#15]

**Comment by DariaUlanova** [comment]
Пытаюсь вынести действия для `issue` в `issues#show`. Для этого в роутах добавила

```
resource :issues, only: [:new, :create, :show] do
  ...
  get ':number', to: 'issues#show', as: :'show'
end
```

По адресу `/boards/huboardtest/issues/2` во вьюхе `issues/show` хочется вывести, например, `@issue.name`. Но как вытянуть `@issue` по его номеру `params[:number]` в контроллере?

По аналогии с `boards_controller` вытягиваю все `@issues`

```
@issues = github_api.board_issues(@board)
```

А конкретный `@issue` не понимаю как вытянуть.

**Comment by DariaUlanova** [comment]
Нашла `github_api.issue(@board, 2)`, есть же готовый метод =)

**Comment by DariaUlanova** [comment]
В папку public добавила папку octicons - иконки гитхаба. При деплое, наверное, нужно это учесть.
