### ISSUE TITLE
Write life cycle kanban-team

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#151]

**Comment by blackchestnut** [comment]
@Sfolt посмотри пожалуйста в драйве описание, какие моменты написаны непонятно, или что-то забыл?

**Comment by blackchestnut** [comment]
@Sfolt посмотри пожалуйста в драйве описание, какие моменты написаны непонятно, или что-то забыл?

**Comment by DariaUlanova** [comment]
@blackchestnut, написала комментарий в ГД.

**Comment by blackchestnut** [comment]
@Sfolt отписался, давай обсудим при встрече.

**Comment by DariaUlanova** [comment]
@blackchestnut Ок, давай
