### ISSUE TITLE
Write life cycle scrum-team

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#152]

**Comment by blackchestnut** [comment]
@Sfolt начал описывать добавил папку Agile Season в google drive.

**Comment by blackchestnut** [comment]
@Sfolt закончил коротко описание, посмотри пожалуйста откомменть что криво написано, или не понятно.

**Comment by DariaUlanova** [comment]
Ок, в целом все понятно по функционалу скрама. Непонятно, как на практике люди будут пользоваться разными бордами. Будут заводить один и тот же проект для обоих бордов, или борды будут взаимосвязанными и будут иметь одну доску с тикетами, но разные настройки и графики?

**Comment by blackchestnut** [comment]
@Sfolt борд должен быть один. Тип борда определяется при создании и не меняется, если команда хочет поменять подход в работе, то тут только пересоздание борад. В скраме физически борд один, но с каким-то функционалом выбора спринта. При смене спринта отображаются тикеты, которые были в том спринте (там по факту арихв не нужен). График Burndown Chart так же привязан к спринтам, а вот график по скорости в спринтах "глобальный" (каждая точка на нем это производительность в спринте в story points или в днях).

**Comment by blackchestnut** [comment]
@Sfolt борд должен быть один. Тип борда определяется при создании и не меняется, если команда хочет поменять подход в работе, то тут только пересоздание борад. В скраме физически борд один, но с каким-то функционалом выбора спринта. При смене спринта отображаются тикеты которые были в том спринте (там по факту арихв не нужен). График Burndown Chart так же привязан к спринтам, а вот график по скорости в спринтах "глобальный" (каждая точка на нем это производительность в спринте в story points или в днях).
