### ISSUE TITLE
Pull requests don't appear like an issue on the board as it was before. Is it ok?

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#159]

**Comment by blackchestnut** [comment]
Изначально я подумал, что это даже лучше что пулреквест появляется на борде, т.к. это задача, однако в процессе работы это выглядит следующим образом:
1. задача из процесса переводится в тест и создается пулреквест
2. появляется незаметно новая задча по пулреквесту в 1й колонке
3. ее диплоим и проверяем на продакшене
4. тем временем задача автоматом закрывается в первой колонке
5. протестировали хотим перевести в "готово" и видим что что-то новое да и еще закрытое, да еще и автоматом

В общем пока не понятно как их увезать, т.к. первые колонки могут в общем случае не относиться к разработке, можно было бы как-то это обыграть в канбане, но вот в скраме новые задачи внутри итерации появляться не могут, а тут получается само создается.

В общем я их пока спрятал, возможно в процессе использования наткнемся на то как их можно аккуратно вписать в нашу доску.

**Comment by DariaUlanova** [comment]
Ok, agreed
