### ISSUE TITLE
Archive button 

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#162]
![agile season 2015-02-08 23-05-25](https://cloud.githubusercontent.com/assets/2400100/6098174/67709790-afe7-11e4-9c6c-18494bc6c7ab.png)

**Comment by DariaUlanova** [comment]
Uups

**Comment by DariaUlanova** [comment]
Uups

**Comment by blackchestnut** [comment]
@Sfolt Are comments duplicated?

**Comment by DariaUlanova** [comment]
It is bug #168

**Comment by DariaUlanova** [comment]
The question could be "Do comments duplicate?" or maybe with passive voice "Are comments duplicated?". A sentence with question mark starts from a verb.

**Comment by DariaUlanova** [comment]
The question could be "Do comments duplicate?" or maybe with passive voice "Are comments duplicated?". A sentence with question mark starts from a verb.
