### ISSUE TITLE
Remove comment

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#164]

**Comment by blackchestnut** [comment]
test

**Comment by blackchestnut** [comment]
test

**Comment by blackchestnut** [comment]
@Sfolt попробовал немного по удалять/редактировать заметил за собой, что приходится включать вестибулярный аппарат чтобы поймать кнопочки в видимом состоянии. Возможно это у меня только так, что если немного расширить область при наведении на которую будут кнопочки видны, чтобы упростить траекторию ведения мышки к ним?
![monosnap 2015-02-19 06-35-40](https://cloud.githubusercontent.com/assets/2400100/6261541/5b68c5f8-b802-11e4-9d91-39b88d2236cd.png)

**Comment by DariaUlanova** [comment]
@blackchestnut ок

**Comment by blackchestnut** [comment]
Актуально только для самого нижнего комментария.

**Comment by blackchestnut** [comment]
test
