### ISSUE TITLE
Deadline for issue

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#171]

**Comment by blackchestnut** [comment]
add column `deadline_at` to the `issue_stats`

**Comment by blackchestnut** [comment]
or `due_date_at`

**Comment by blackchestnut** [comment]
@Sfolt как лучше сделать? Раскомментировал .due-date
![agile season 2015-03-14 22-29-39](https://cloud.githubusercontent.com/assets/2400100/6653218/caeed8e6-ca99-11e4-9a9d-ff73664bf91a.png)
(не обращай внимание, что нет времени после даты - временно убрал)

По клику сделал раскрытие календаря
![agile season 2015-03-14 22-32-03](https://cloud.githubusercontent.com/assets/2400100/6653223/f81e7466-ca99-11e4-9b6d-22ad0b006380.png)

Но вот когда еще эта дата не установлена, то как сделать отображение этого блока чтобы можно было установить эту дату?

Сейчас так
![agile season 2015-03-14 22-33-28](https://cloud.githubusercontent.com/assets/2400100/6653224/2b032b42-ca9a-11e4-8f0c-586519186875.png)
но это скорее набросок, чтобы было по чему кликать.

**Comment by blackchestnut** [comment]
@Sfolt или же тут планировалось только отображение, а установка там где labels и назначение?

**Comment by DariaUlanova** [comment]
@blackchestnut я бы все действия пока добавляла в колонку с лейблами в виде стандартных кнопок (в кнопку можно вставить иконку часов, чтобы различать кнопки). И тогда, думаю, не нужно делать кликабельным оранжевый лейбл.

**Comment by blackchestnut** [comment]
@Sfolt ок

**Comment by blackchestnut** [comment]
@Sfolt в общем сделал в первом приближении, посмотри своим взглядом, если будет желание поправь на свое усмотрение. Так же думаю нужно будет в самом конце посмотреть на то как выглядит тикет на борде - возможно там то же нужно будет подумать что-куда положить (due date не знал куда положить, поэтому сдвинул просто в права, после заголовка как в модальном окне смотрелось не очень при заголовках разной длинны).
