### ISSUE TITLE
Add new column

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#173]

**Comment by blackchestnut** [comment]
@Sfolt пока не добавляй колонки в борд agilesaeaon т.к. там график CFD нужно будет доработать для появления новой колонки в случае перемещений.

**Comment by blackchestnut** [comment]
@Sfolt не обращай пока внимание на @houndci - похоже они что-то поменяли и настройки его слетели, он сейчас ругается всем чем попало - по умолчанию.

**Comment by DariaUlanova** [comment]
@blackchestnut ok
