### ISSUE TITLE
Remove column

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#174]

**Comment by blackchestnut** [comment]
@Sfolt я ограничен в фантазии, поэтому получился не шик-блеск :) в дальнейшем можно будет причесать этот ужас.
![agile season 2015-02-22 21-43-33](https://cloud.githubusercontent.com/assets/2400100/6319820/2e55ef8c-badc-11e4-99cf-2222da826f8b.png)

**Comment by DariaUlanova** [comment]
@blackchestnut Нормально! :)

**Comment by DariaUlanova** [comment]
@blackchestnut, как ты относишься к такому, например, как в трелло редактировать можно кликнув по тексту, вместо кнопки 'edit' или карандаша?

**Comment by blackchestnut** [comment]
@Sfolt вообще если говорить именно про колонки, то нейтрально, т.к. в трелло редактировал колонку лишь раз. Думаю эта операция не частая и даже если бы мы ее спрятали за edit + password сильно никто не страдал. А вот если говорить про issue, то тут бы я подумал, что было бы не плохо, т.к. например заголовок и описание я частенько редактирую, а попасть только в карандашек тяжело.
