### ISSUE TITLE
Slider with activities

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#176]

**Comment by blackchestnut** [comment]
list activities: http://agileseason.com/boards/agileseason/agileseason/activities

**Comment by DariaUlanova** [comment]
@blackchestnut
What have we decided about activities from github API for example 'smb pushed to master'? Should we do these on current MVP or next?

**Comment by DariaUlanova** [comment]
@blackchestnut 
I think our slider with activities should look like
![2015-04-06 14 02 15](https://cloud.githubusercontent.com/assets/6046764/7004349/b92609fa-dc72-11e4-950a-6047168fc706.png)
![2015-04-06 14 01 52](https://cloud.githubusercontent.com/assets/6046764/7004348/b901beb0-dc72-11e4-819c-9e53247b51d7.png)

**Comment by DariaUlanova** [comment]
Bug
![2015-04-07 8 46 59](https://cloud.githubusercontent.com/assets/6046764/7017622/cf07f25c-dd02-11e4-87a3-ca40a4be38f7.png)

**Comment by DariaUlanova** [comment]
@blackchestnut maybe the activitiy list should be limited, for example show only last 30 activities? And after last activity is scrolled out the new 30 activities is shown? How do you think?

**Comment by DariaUlanova** [comment]
@blackchestnut I've not finished the issue yet :)

**Comment by blackchestnut** [comment]
@Sfolt 
Fail... :) 
У меня сработал тригер - тикет в review, значит можно замержить :)

**Comment by DariaUlanova** [comment]
@blackchestnut ok, в следующий раз не буду ранше времени

**Comment by blackchestnut** [comment]
@Sfolt можно переименовать Review в To Deploy, или тег добавить - как тебе удобнее?

**Comment by DariaUlanova** [comment]
@blackchestnut To deploy =)
