### ISSUE TITLE
Attach files to issue#body and comment#bydy

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#177]
- [x] Simple Attach
- [x] View on Github

![uploads/2d55d0ab-9e1a-433e-8de9-4b99372273f7/agileseason.png](https://agile-season-production.s3.amazonaws.com/uploads/2d55d0ab-9e1a-433e-8de9-4b99372273f7/agileseason.png)

**Comment by blackchestnut** [comment]
@Sfolt возможно есть смысл в начале сделать только картинки, если конечно это имеет значение и ускорит (другие файлы как правило это более редкое использование).

**Comment by DariaUlanova** [comment]
@blackchestnut ok

**Comment by blackchestnut** [comment]
@Sfolt 

> Добавление изображения или файла в попапе (миниатюра со ссылкой на картинку в исходном размере, которая откроется в соседней вкладке или ссылка на скачивание файла). Иконка файла в миниатюре или картинка.

Не совсем понял, по описанию. Давай я закоммичу текущий топорный вариант, а потом при случае обсудим.

**Comment by blackchestnut** [comment]
Test upload:
![uploads/2d55d0ab-9e1a-433e-8de9-4b99372273f7/agileseason.png](https://agile-season-production.s3.amazonaws.com/uploads/2d55d0ab-9e1a-433e-8de9-4b99372273f7/agileseason.png)

**Comment by DariaUlanova** [comment]
testing file uploading
![uploads/27dd68cc-45f6-42f0-beee-07b94a112a1f/Снимок экрана 2015-04-08 в 19.23.01.png](https://agile-season-production.s3.amazonaws.com/uploads/27dd68cc-45f6-42f0-beee-07b94a112a1f/Снимок экрана 2015-04-08 в 19.23.01.png)

**Comment by DariaUlanova** [comment]
@blackchestnut cool, drag'n'drop works if drag file on input

**Comment by DariaUlanova** [comment]
@blackchestnut did you draw the leaf by your hands, didn't you?

**Comment by blackchestnut** [comment]
> @blackchestnut did you draw the leaf by your hands, didn't you?

@Sfolt, yep. It's sketch :) Drew long ago, while thought about prototype and its name.
