### ISSUE TITLE
Filter issues by assigned

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#180]

**Comment by blackchestnut** [comment]
@Sfolt как думаешь - как это в минимальном виде должно выглядеть? :)

**Comment by blackchestnut** [comment]
По-моему мы обсуждали 2а варианта, когда тикеты прячутся и когда затемняются лишние. В затемнении есть минус - если тикетов много, то тот что нужен может быть в самом низу и до него листать серые придется. Но есть и плюс сразу видно что фильтр включен - хотя это можно думаю и по другому обыграть. А вот как должен выглядеть сам контрол фильтра? Есть вариант пойти сразу как в трелло добавив в меню поле ввода и учиться реагировать на @ для назначенных и т.д., все равно потом делать поиск по тексту и куда-то это поле ввода нужно будет вставлять. @Sfolt что думаешь?

**Comment by DariaUlanova** [comment]
@blackchestnut

Нужно научить систему распознавать пользователей по `@`. 

Когда фильтрую тикеты по человеку, скорее всего я ищу какой-то конкретный тикет, или хочу посмотреть, сколько всего тикетов на мне (или на ком-то). Нужно ли в этом случае мне видеть расположение на борде?

Если нет, то можно показывать тикеты один за другим — списком.

Если да, то я это представляю так. Тикеты, которые не на мне, станут бледными, а мои — останутся белыми. Чтобы был контраст, можно изменить цвет фона борда.

Еще будет поиск/фильтр по иным параметрам, например, я хочу просмотреть все, что в архиве — этих тикетов на борде нет.

Я бы сделала два вида отображения тикетов: на борде и списком.

**Comment by blackchestnut** [comment]
@Sfolt под "списком" ты имеешь ввиду как в трелло?

![welcome board trello 2015-04-26 18-13-52](https://cloud.githubusercontent.com/assets/2400100/7337810/05bb82cc-ec40-11e4-9f79-0ca35542c033.png)
