### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory - nodejs

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#192]

**Comment by blackchestnut** [comment]
change server

**Comment by DariaUlanova** [comment]
@blackchestnut, что это значит, не хватает оперативной памяти?

**Comment by blackchestnut** [comment]
@Sfolt на серваке для диплоя переодически не хватает памяти, приходится перезагружаться, сегодня начал переезд на другой где оперативки побольше.

**Comment by DariaUlanova** [comment]
@blackchestnut, на какой?

**Comment by blackchestnut** [comment]
@Sfolt хочу чтобы у него был чистый 1Гб места в оперативке под все воркеры и sidekiq, сейчас получается меньше и иногда ему не хватает при некоторых диплоях (когда bundle + упаковка js/css) т.к. остается 150 метров всего свободно.

**Comment by blackchestnut** [comment]
```
deploy@localhost:~$ free
             total       used       free     shared    buffers     cached
Mem:       1014660     408972     605688       7200       9136      70164

```

**Comment by blackchestnut** [comment]
Проблема еще актуальна, память постепенно полностью забивается. Нужно выяснить чем.

**Comment by blackchestnut** [comment]
Буду открывать новые тикеты. Для начала подключить newrelic #207
