### ISSUE TITLE
multiply comments

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#215]
нужно несколько раз походить по бордам, а потом выбрать тикет с комментариями.

**Comment by blackchestnut** [comment]
не важно по каким страница ходить

**Comment by DariaUlanova** [comment]
@blackchestnut поняла, то есть каждый раз по `page:change` копится `$(document).on 'click', '.show-issue-modal'`, как-то так?

**Comment by blackchestnut** [comment]
@Sfolt при обчном хождении по страничкам объект document не меняется. При возврате не show добавлялось еще одно событие.
