### ISSUE TITLE
Sidekiq everywhere...

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#221]

**Comment by blackchestnut** [comment]
![agileseason deploy localhost ssh 150x38 2015-03-03 08-50-54](https://cloud.githubusercontent.com/assets/2400100/6457176/9e31bf0a-c182-11e4-8de9-7d82caac2bfd.png)

**Comment by blackchestnut** [comment]
Странно...
![current ssh 150x38 2015-03-09 21-29-12](https://cloud.githubusercontent.com/assets/2400100/6561595/6df5c37e-c6a3-11e4-92bc-bcdf379c4e89.png)

**Comment by DariaUlanova** [comment]
@blackchestnut я не поняла)

**Comment by blackchestnut** [comment]
@Sfolt да это я больше сам с собой... почему-то htop показывает много процессов у sidekiq, а если посмотреть тут же через ps, то там один... возможно во втором случае ключи aux остальные фильтруют... в общем жду пока опять диплой не сможет пройти.
