### ISSUE TITLE
Restructure assets folders

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#226]

**Comment by blackchestnut** [comment]
@Sfolt я начал сильно путаться как у нас разделяются стили и js по страничка и блокам. Мне не совсем нравится подход который у нас в uptimus с разделением block/page. Как думаешь как нам можно немного реорганизовать подход к созданию блоков и стилей к ним, а так же стилей к страницам, чтобы можно было легче понимать что где находится.

**Comment by blackchestnut** [comment]
@Sfolt для меня сейчас следующая проблема обнаружилась:
1. один и тот же css-класс может находится в разных css файлах, поэтому не знаешь куда добавлять
2. струкутра asset-ов не повторяет структуру вью, поэтому тяжело понять куда добавлять
3. не понятно когда стоит выделять что-то в блок

@Sfolt давай как-нибудь за заваркой чая обменяемся мыслями на этот счет, чтобы долго не писать. Такая же беда у меня и в Аптимусе, спасает только полнотекстовый поиск.

**Comment by DariaUlanova** [comment]
@blackchestnut скорее всего путаница в цсс-ках попапа тикета. Согласна, что нужно мне их отрефакторить.

Вообще у меня получаются 3 вида цсс-ок:
1. для конкретной страницы,
2. для блоков - повторяющихся элементов на разных страницах,
3. какие-то глобальные стили, которые лежат часть в лейаутах, часть в глобалс. 

Меня скорее пункт 3 смущает, даже в аптимусе. Давай завтра, если у тебя найдется минутка, обсудим.

**Comment by blackchestnut** [comment]
Договорились до следующего:
1. Стили `layouts/l-*.sass` больше сковывают и замедляют чем ускоряют и помогают. При частых изменениях верстки они покрываются "мхом" и не используются. Все что в них полезного остается скорее идет в `globals/*.sass`
2. Блоки нужны, а так же нужен их префикс `b-*.sass`, однако, благодаря использованию mixin их  целесообразно свести к минимуму.
3. Для стилей страниц удобнее повторять структуру `controller/view`. Оставляем для них отдельную папочку, а дальше `page/controller_name/view_name.sass`. В случае, если вью не много или стили для них не целесообразно разделять, то остается просто `page/controller_name/controller_name.sass`.

@Sfolt посмотри пожалуйста, я не ошибся и ничего не забыл?

**Comment by DariaUlanova** [comment]
@blackchestnut вроде все так, vendor и lib остаются на своих местах.

**Comment by DariaUlanova** [comment]
@blackchestnut только в третьем пункте так 

```
page/controller_name/controller_name.sass
```

или так

```
page/controller_name/action( or _partial)_name.sass
```

**Comment by blackchestnut** [comment]
@Sfolt да, точно.
