### ISSUE TITLE
Hide or Alert?

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#247]
Как лучше делать - прятать управляющие элементы если недостаточно прав для их использования, или будем делать к.л. обработчик глобальный, который бы нам говорил, что прав не хватает?

Вопрос появился полсе того, как убрал несколько элементов с issue_modal начинает смотреться хуже (действия справа + добавление комментария). Остальные пока оставил, но они сейчас кидают 500 и это не хорошо - нужно будет исправлять.

**Comment by DariaUlanova** [comment]
@blackchestnut думаю, нужно показывать пользователю только то, что ему доступно.

**Comment by blackchestnut** [comment]
@Sfolt ok
