### ISSUE TITLE
Remove Board and Issue actions if permissions not enough

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#261]

**Comment by blackchestnut** [comment]
@Sfolt, как думаешь лучше элементы совсем прятать, или же все таки их делать disabled?

**Comment by blackchestnut** [comment]
- [x] column settings
- [x] drag and drop
- [x] move to in issues#show
- [x] edit title

**Comment by DariaUlanova** [comment]
@blackchestnut, не должно быть элементов управления, которыми нельзя пользоваться.

**Comment by blackchestnut** [comment]
@Sfolt ок, на странице тикета оставил контрол с указанием в какой колонке он находится, т.к. без него не красиво совсем было.

**Comment by DariaUlanova** [comment]
@blackchestnut, ок, согласна.
