### ISSUE TITLE
Current time zone

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#264]
@blackchestnut 
As far as I understand we need set up current time zone on the server to see in interface our current time, don't we?

**Comment by blackchestnut** [comment]
@Sfolt для тех дат, что выставляет пользователь мы можем всегда использовать utc и тогда не важно в какой зоне, а вот для того, что отображаем пользователю мы сами, тут нужно подумать как это делают в github-е например, там выставление зоны нет. На графике активности там идет отсчет по америке, а вот в комментах хз как они определили GTM +03 для меня - возможно по кредитке?

**Comment by blackchestnut** [comment]
@Sfolt добавить поле с настройкой не проблема, здорово придумать взять откуда-нибудь значение не спрашивая пользователя. Возможно браузер?

**Comment by blackchestnut** [comment]
@Sfolt так же для начала можно писать в формате `10 min ago`, `just now` и т.д., но в title все равно лучше полное время указать.

**Comment by blackchestnut** [comment]
@Sfolt можно попробовать
https://github.com/kbaum/browser-timezone-rails, хотя он внутри себя использует https://bitbucket.org/pellepim/jstimezonedetect, так что возможно легче бдует юзать напрямую:
http://thisbythem.com/blog/clientside-timezone-detection/
