### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by morr** [agileseason/agileseason-v1#265]
![monosnap 2015-04-09 00-59-03](https://cloud.githubusercontent.com/assets/134610/7056344/a0420050-de53-11e4-990f-9a1c95cb5074.png)

I had been moving tickets between columns

**Comment by DariaUlanova** [comment]
There was @board in new menu item (activities) but the value of the @board was nil. I've put the item in `if @board` clause.
