### ISSUE TITLE
How to show that Issues added if issues more than screen?

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#270]

**Comment by DariaUlanova** [comment]
@blackchestnut What do you mean?

**Comment by DariaUlanova** [comment]
@blackchestnut I don't understand what you mean =)

**Comment by blackchestnut** [comment]
@Sfolt Если в колонке бэклога количество Issues-ов такое, что они уже не вмещаются в экран и появляется скролл - то при добавлении новой Issue не понятно пороизошло ли что-нибудь. Дополнительно, в одном из проектов у меня в backlog-е около 50 тикетов и чтобы добраться до нужно долго листать.

**Comment by DariaUlanova** [comment]
@blackchestnut ok, after adding a new issue may be put on the top of its column and save the order of the column.

**Comment by blackchestnut** [comment]
@Sfolt,
yes, it's better
