### ISSUE TITLE
Activity slider mast be limited

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#271]

**Comment by DariaUlanova** [comment]
![2015-04-07 8 46 59](https://cloud.githubusercontent.com/assets/6046764/7073205/74ab6614-defa-11e4-95bd-e2042445ee7d.png)

**Comment by DariaUlanova** [comment]
@blackchestnut maybe the activitiy list should be limited, for example show only last 30 activities? And after last activity is scrolled out the new 30 activities is shown? How do you think?

**Comment by blackchestnut** [comment]
@Sfolt, as you wish :). I think, limit with pagination by scroll much better than loading `Activity.all` at once.
