### ISSUE TITLE
Huboard compatibility

### ISSUE THREAD

**Issue by morr** [agileseason/agileseason-v1#272]
I would like to try to use Agileseason but since it is currently not fully functional it would be great if Agileseason would be compatible with Huboard.
1. Preserve issues position in columns.
2. Preserve issues rows sort ordering.

I.e. store issue status not only in internal agileseason database but also store status in issue body content like Huboard does.
![monosnap 2015-04-10 01-41-22](https://cloud.githubusercontent.com/assets/134610/7078551/d2aa2f2a-df22-11e4-92e1-9935cc88dfe7.png)

Huboard:
![shikimori huboard 2015-04-10 01-35-55](https://cloud.githubusercontent.com/assets/134610/7078461/f346776c-df21-11e4-813f-55d3f51ca422.png)

Agileseason:
![agile season 2015-04-10 01-35-33](https://cloud.githubusercontent.com/assets/134610/7078456/e7874ea6-df21-11e4-8cf8-75c6f25550f7.png)

![z](https://cloud.githubusercontent.com/assets/134610/7078594/1259a1d2-df23-11e4-82f0-07ce5a0251a1.jpg)

**Comment by blackchestnut** [comment]
@morr,
unfortunately this is not possible now.
Huboard has a simple functional movements columns and sorting tickets.
It is easy save the small data in the comments. In the beginning we did the same.
But it's an ugly way:
1. The columns are stored in the tags Github - requires synchronization each time. Easy to break by removing the tag via Github.
2. Sorting (in our case, a lot of things) can be broken by changing the comment in the body.
3. Any change triggers a change in the body - it is looks like:
![shikimori 2015-04-13 20-38-11](https://cloud.githubusercontent.com/assets/2400100/7121548/e297f892-e21d-11e4-9ebc-613bfaa33e1e.png)

Please write a list of features that you need before to migrate to Agile Season.

**Comment by morr** [comment]
@blackchestnut 

![agile season 2015-04-13 23-22-21](https://cloud.githubusercontent.com/assets/134610/7124720/f949a034-e233-11e4-85fd-4dce54e427ce.png)
![agile season 2015-04-13 23-23-10](https://cloud.githubusercontent.com/assets/134610/7124738/28273fe2-e234-11e4-96a9-12a8f6642de9.png)

Drag'n drop images upload (try `shiki_file.js.coffe`)
Github checkbox lists support [ ]
![shikimori huboard 2015-04-13 23-19-59](https://cloud.githubusercontent.com/assets/134610/7124678/a297d850-e233-11e4-8399-1fce06d7111e.png)

**Comment by morr** [comment]
Personally i don't care about agile statistics graphs. I think that another killer feature of agileseason could be providing access to issues for users who does not have access to repository.
Ability to read issues. Ability to create issues. Ability to comment issues. Ability to move issues.

**Comment by blackchestnut** [comment]
@morr, thanks.
About providing access:
We thought about it. However, GitHub does not allow data without github_token with full rights. it will have to be stored in the base - it will reduce security.
Perhaps if it was a common problem then GitHub added role with access only to the bugtrack.
We keep this in mind and try to find more elegant solution.
