### ISSUE TITLE
Modal window opens by button click from board.

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#273]
Click by buttons - open modal :(

**Comment by blackchestnut** [comment]
@Sfolt,
from ea55f1f54e72af4fa34d7ab46579e7afd99d2742

**Comment by blackchestnut** [comment]
@Sfolt,
don't repeats, maybe cache...

**Comment by blackchestnut** [comment]
@Sfolt,
ah, need change column before.

**Comment by blackchestnut** [comment]
...via modal window

![agile season 2015-04-15 15-30-06](https://cloud.githubusercontent.com/assets/2400100/7158596/576560e4-e384-11e4-914e-451881241445.png)

**Comment by DariaUlanova** [comment]
@blackchestnut How can I repeat the bug?

**Comment by blackchestnut** [comment]
@Sfolt,
1. Click by ticket (which is not in last column - Done)
2. Move to Done (in modal)
3. Close modal window
4. Click by close button from board

**Comment by blackchestnut** [comment]
@Sfolt,
Can I megre?

**Comment by DariaUlanova** [comment]
@blackchestnut yep
