### ISSUE TITLE
Prettify all dropdowns

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#283]

**Comment by DariaUlanova** [comment]
@blackchestnut,

Тест развалился, вряд ли из-за моих изменений по верстке. Еще мои коммиты не попали в кодшип.

![uploads/2d6fb5dd-e11e-49c3-b613-3f493361fbdc/Снимок экрана 2015-07-07 в 0.58.10.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2d6fb5dd-e11e-49c3-b613-3f493361fbdc%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-07-07%20%D0%B2%200.58.10.png)

**Comment by blackchestnut** [comment]
@Sfolt, видимо криво написан - не обращай внимание, возможно это из-за времени у тебя так попало. На билдсервере все ок.

**Comment by blackchestnut** [comment]
@Sfolt, очень красиво получилось!
Ты модальное оно при создании нового issue не закрываешь после сохранения для множественного добавления подряд?

**Comment by DariaUlanova** [comment]
@blackchestnut, да, чтобы несколько подряд добавлять. Подумала, что меня бы раздражало каждый раз по новой открывать. После добавления поле очищается, и срабатывает фокус.

**Comment by blackchestnut** [comment]
@Sfolt, согласен, удобно когда несколько подряд добавляешь, но вот если одну, то приходится закрывать. 

Заметил, за собой что сначала не заметил, что Тикет добавился и подумал, что форма не работает.

**Comment by DariaUlanova** [comment]
@blackchestnut сделала закрытие формы по `ajax:success` после создания тикета.

**Comment by blackchestnut** [comment]
@Sfolt, идея с постоянным открытым слоем на самом деле хорошая, как бы ее обыграть, чтобы было удобно в обоих случаях. Первое что приходит на ум это запилить галочку, типа "массовый ввод", "держать открытой" что-то под вечер слова не идут. Возможно есть способ лучше типа нажмешь enter закроется, а нажмешь cmd+enter от создастся и не закроется, но это для примера и в порядке бреда.

**Comment by blackchestnut** [comment]
@Sfolt, по поводу незаметного добавления в будущем возможно если анимации какой-то добавить при добавлении на борде, тогда будет заметно. Возможно анимация будет интересна и при изменении другими борда, чтобы тикеты не телепортировались мгновенно.

**Comment by blackchestnut** [comment]
@Sfolt, как идея для размышления - иногда при добавлении хочется сразу назначить и куда-нибудь передвинуть. Не уверен что хорошая идея перегружать слой для добавления нового тикета - попробуй понаблюдать за собой, как действуешь.

**Comment by DariaUlanova** [comment]
@blackchestnut, ok. Над анимацией думала, со временем приделаю, согласна, что нужно помечать ново добавленный тикет.

Мне сейчас не нравится попап добавления тикета, так как он сейчас — что-то промежуточное между миниатюрой и страницей тикета. Хотелось сделать добавление также страницей тикета, только с пустым полем заголовка, так сразу можно и перенести на иную колонку и пользователя назначить. Остановило меня мысль, что добавление станет медленней.

Может верстку попапа переделать так, чтобы выглядет он как страница тикета, но без кнопок назначения, перенесение на др колонку, комментирования…, и по аякс саксессу заголовка тикета добавить выше перечисленный функционал. Это все будет соот-о на js.

**Comment by blackchestnut** [comment]
@Sfolt, то что сейчас быстрое добавление это здорово. В том, что ты говоришь есть логика - тогда и интерфейс одинаковый для добавления и редактирование - трудно сказать пока сходу. Можно было бы попробовать в отдельной ветке - но это достаточно трудоемко, чтобы экспериментировать помоему. А мне понравился твой текущий вариант - например лейблы легко добавить когда они сразу в списке (правда мы не знаем сколько у наших пользователей этих лейблов будет, я в некоторых репозиториях такую кучу встречал).
ИМХО похоже все дороги идут в сторону модального окна без отдельной страницы issues#show :)

**Comment by blackchestnut** [comment]
@Sfolt давай я попробую поюзать пока ты в отпуске - как вернетесь, будет хоть на чем основываться.

**Comment by DariaUlanova** [comment]
@blackchestnut, ok
