### ISSUE TITLE
Prettify settings page

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#284]

**Comment by blackchestnut** [comment]
wait #360

**Comment by blackchestnut** [comment]
wait #626

**Comment by DariaUlanova** [comment]
@blackchestnut
I think it would be better to remove the column settings from the board to the settings page.
Users seldom use it, maybe only once.
The board will load faster a bit.

What do you think?

**Comment by blackchestnut** [comment]
@Sfolt How users find that the settings for the columns are there?

**Comment by DariaUlanova** [comment]
@blackchestnut 
There is only one menu with 3 items, one is settings.
A user has to see all the items and click 'settings' at list once to find out what these settings for at the very beginning of his working in AS.
We also can rename to 'board settings' for more understanding.

As a compromise we can leave some settings on the board (autoassign and WIP) and the rarest settings move to the settings page. But I think it is not necessary yet while AS has a few settings. When AS has many settings it will make a sense.

**Comment by blackchestnut** [comment]
@Sfolt tell me more about this at the meeting

**Comment by DariaUlanova** [comment]
@blackchestnut ok

**Comment by DariaUlanova** [comment]
@blackchestnut

Look at the screen. What do you think about it? Is everything clear?
![uploads/2015-09-05/40688718-969b-45f5-9f3a-9798d1c07a40/settings.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-09-05%2F40688718-969b-45f5-9f3a-9798d1c07a40%2Fsettings.png)

**Comment by DariaUlanova** [comment]
@blackchestnut

If I move an empty column, always 2 columns change their positions. Is it ok, if the second one is not empty?

**Comment by blackchestnut** [comment]
@Sfolt, 

> If I move an empty column, always 2 columns change their positions. Is it ok, if the second one is not empty?

Классное замечание! Думаю можно все же попробовать убрать это ограничение оставив предупреждение и разрешить перемещать с тикетами в колонке.

Больше всего я переживаю за график CFD, но посмотрев, как там сохраняю данные:

```
        arr << {
          column_id: column.id,
          issues: count,
          issues_cumulative: total_issues
        }
```

ничего страшного не должно произойти с точки зрения кода, однако от статистики после конкретной перемешки думаю будет мало толку. Нужно подумать на тему ее сброса в будущем.

**Comment by blackchestnut** [comment]
@Sfolt, выглядит страничка здорово. Единственно складывается ощущение, что заголовок про синхронизацию относится ко всем 3м кнопкам. Думаю его смысл вообще можно слепить с описанием справа от кнопки "Create hook".

Т.к. место позволяет можно написать WIP без сокращения на всякий случай для тех кто все таки не знает что это например "Work in progress limits ..." или просто "Work in progress, from ..."

**Comment by blackchestnut** [comment]
@Sfolt, как будет выглядеть строчка если включить и автоназначение и автозакрытие - текст через запятую?

**Comment by blackchestnut** [comment]
@Sfolt, куда ведет ссылка statistic data?

**Comment by blackchestnut** [comment]
@Sfolt, хочется глянуть на код - который обновляет поля, интересно как сделала.

**Comment by DariaUlanova** [comment]
@blackchestnut 

> как будет выглядеть строчка если включить и автоназначение и автозакрытие - текст через запятую?

Так точно

> куда ведет ссылка statistic data?

Пункт в меню metrics

> хочется глянуть на код - который обновляет поля, интересно как сделала

Еще доделываю, сохраняю через плагин, который ты добавил js-patch

**Comment by blackchestnut** [comment]
@Sfolt, ok

**Comment by blackchestnut** [comment]
@Sfolt, из мелочей:
![uploads/2015-09-06/61ee165d-a1b4-44cb-8e69-82fe403ff0ef/Monosnap 2015-09-06 18-24-01.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-09-06%2F61ee165d-a1b4-44cb-8e69-82fe403ff0ef%2FMonosnap%202015-09-06%2018-24-01.png)

**Comment by blackchestnut** [comment]
@Sfolt как-то непонятно работает галочка `is_public`, попробуй на борде `test_dev`
![uploads/2015-09-06/ace42b08-1e23-458d-bb1f-901f1d12b741/Monosnap 2015-09-06 18-31-24.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-09-06%2Face42b08-1e23-458d-bb1f-901f1d12b741%2FMonosnap%202015-09-06%2018-31-24.png)

**Comment by blackchestnut** [comment]
@Sfolt сломалось :( #672

**Comment by blackchestnut** [comment]
@Sfolt, #672 - это глюк видимо

**Comment by DariaUlanova** [comment]
@blackchestnut
Все-таки настраивать список колонок по горизонтали не удобно, ведь перед глазами был борд с горизонтальным расположением. Как думаешь, может по-горизонтали лучше?

**Comment by blackchestnut** [comment]
@Sfolt думаю, что по интуитивности лучше чем было на борде не сделаешь, т.к. там ты видишь сразу, что значит влева и в права, что у тебя твориться в этой колонке и какой wip исходя из текущей ситуации нужен. Плюс связь настроек с непосредственным объектом, который настраиваешь. Об этом мы говорили. Что смущало, так это возможно редкий кейс в редактировании колонки (а ссылка все время маячит) и то, что при первом знакомсвте с системой пользователь охотнее кликнет в большую Settings, чем в маленькую шестеренку на колонке.

Что заметно стало после использования:
На текущий момент хуже стало с осознанием пользователя, что можно сделать с колонкой 
1. если не наведешь то даже не узнаешь, что есть маленькая ссылочка шестиренки:
![agile season 2015-09-10 07-13-08](https://cloud.githubusercontent.com/assets/2400100/9780068/662343ae-578c-11e5-9f1f-6e68bceeb2f7.png)
2. пока не кликнешь не узнаешь что есть еще настройки
3. то что нужно траспонировать колонки при переносе это самое меньшее из зол, хотя согласен, что это доп.усилие над собой.

P.S. Если подитожить, то вариант с меню на борде мне ближе. Шестеренки не очень нравились повторяющиеся. Вот если бы можно было сделать их менее бросающимися в глаза, но вто же время не совсем незаметными - думаю это оптимальный вариант. Хотя последнее можно будет решить в помощи частично (я подумываю перенести странички с описаним фич в странички wiki на гитхабе).

**Comment by blackchestnut** [comment]
@Sfolt может оставить оба варианта, или это перебор?
Как будут пользователи можно посмотреть чем чаще пользуются например.

Есть часть функций которые часто меняются (атоназначение, автозакрытие, wip лимиты), а есть редкие (имя, сортировка), но разделять их по такому принципу я бы не стал, т.к. может сложиться впечатление, что только это можно поменять, а где вторую часть смотреть не понятно.

**Comment by blackchestnut** [comment]
@Sfolt, пропала надпить возле галочки `is_public`, что будет работать только для публичных репозиториев.

**Comment by DariaUlanova** [comment]
@blackchestnut не могу решить, мне тоже пока не нравится текущий вид страницы настроек. Давай продублируем и посмотрим на поведение пользователей. Ютм-метки для микспанела надо расставить?

**Comment by DariaUlanova** [comment]
@blackchestnut

> @Sfolt, пропала надпить возле галочки is_public, что будет работать только для публичных репозиториев.

Лучше показывать эту кнопку для публичных репоз. и скрывать для приватных.

**Comment by blackchestnut** [comment]
@Sfolt согласен, так правильнее.
