### ISSUE TITLE
What's happening with codeship? Do you deploy by your hands?

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#289]

**Comment by DariaUlanova** [comment]
@blackchestnut should I deploy by `cap production deploy` while codeship don't work?

**Comment by blackchestnut** [comment]
@Sfolt,
Suddenly broke :(
Try to repair it. Communicate with support.
Now diploy by hands.

**Comment by blackchestnut** [comment]
@Sfolt,
helped reset dependency cache.
