### ISSUE TITLE
Upload file via drag and drop

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#294]

**Comment by blackchestnut** [comment]
@Sfolt try drag&drop.
What colors or texts need change? What do you think?

**Comment by DariaUlanova** [comment]
Test 

![uploads/b689f071-5173-42a4-b9af-7d8a98b6be37/a0420050-de53-11e4-990f-9a1c95cb5074.png](https://agile-season-production.s3.amazonaws.com/uploads/b689f071-5173-42a4-b9af-7d8a98b6be37/a0420050-de53-11e4-990f-9a1c95cb5074.png)

seems it's ok

**Comment by DariaUlanova** [comment]
Upload 2 images

![uploads/b689f071-5173-42a4-b9af-7d8a98b6be37/Снимок экрана 2015-04-08 в 19.23.01.png](https://agile-season-production.s3.amazonaws.com/uploads/b689f071-5173-42a4-b9af-7d8a98b6be37/Снимок экрана 2015-04-08 в 19.23.01.png)
![uploads/b689f071-5173-42a4-b9af-7d8a98b6be37/Снимок экрана 2015-04-08 в 19.22.55.png](https://agile-season-production.s3.amazonaws.com/uploads/b689f071-5173-42a4-b9af-7d8a98b6be37/Снимок экрана 2015-04-08 в 19.22.55.png)

**Comment by DariaUlanova** [comment]
And it works! Lovely!

**Comment by DariaUlanova** [comment]
@blackchestnut 

> What colors or texts need change? What do you think?

What do you mean? Which colors and which texts need to be changed? Sorry, don't understand.

**Comment by blackchestnut** [comment]
@Sfolt,
Нужно ли что-то поменять в тексте или цветовой схеме этой фичи?
Нормально выглядит во время перетаскивания например?

![uploads/f3cb36c8-3eb9-4806-b1c4-28d586c9d3a1/Agile Season 2015-04-27 14-35-57.png](https://agile-season-production.s3.amazonaws.com/uploads/f3cb36c8-3eb9-4806-b1c4-28d586c9d3a1/Agile Season 2015-04-27 14-35-57.png)

**Comment by blackchestnut** [comment]
@Sfolt, подумал о варианте без надписи, проиграл свое поведение. Оказалось, что я пользуюсь драг&дропом только если вырезаю часть экрана с помощью программы monosnap в остальных случаях если прикрепляю файл то пользуюсь клипом по "selecting them" и указанием пути через shift+cmd+G :) Есть шанс что для кого-то еще это то же стандартное поведение, поэтому если будем делать менее заметный вариант, то нужно функционал открытия окна для выбора файла по клику то же оставить.

**Comment by DariaUlanova** [comment]
@blackchestnut ок, пожалуй, ты прав. Я сейчас переделываю формы ввода/редактирования описания и сообщения. Ссылку attach images сохраню.

**Comment by blackchestnut** [comment]
@Sfolt, если ты сейчас изменяешь поля ввода мне есть смысл фиксить #296 или там то же поменяется и лучше подождать?

**Comment by DariaUlanova** [comment]
@blackchestnut думаю, пока можно не фиксить, я переделываю полностью верстку и js формы.

А что если при перетаскивании будет реагировать поле ввода, а все окно браузера?

**Comment by blackchestnut** [comment]
@Sfolt, а загружать куда если редактируется и тело и комментарий (это конечно не стандартное поведение)? Не вижу ничего плохого, наоборт - далеко не надо тянуть. Не знаю как это сделать, т.к. тут нужно смотреть как себя поведет плагин если дроп будет "далеко" от инпута.
