### ISSUE TITLE
AS board access

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#297]

**Comment by DariaUlanova** [comment]
@blackchestnut Agile Season борд всем доступен, или определенным пользователям? У Андрея в какой-то момент был доступ, недавно доступа не стало.

**Comment by blackchestnut** [comment]
@Sfolt, всем авторизированным в AS. У себя проверил:
![uploads/465fec73-39b9-4e15-bdf6-a18b7bedccc3/Agile Season 2015-04-28 09-06-48.png](https://agile-season-production.s3.amazonaws.com/uploads/465fec73-39b9-4e15-bdf6-a18b7bedccc3/Agile Season 2015-04-28 09-06-48.png)

если не виден, скорее всего нужно смотреть у него

**Comment by DariaUlanova** [comment]
@blackchestnut что значит «авторизированным в AS»? По идее так как у Андрея не было доступа в наш сервис, он и не мог видеть его? Но он почему-то смог войти в борд AS. С другой стороны репозиторий AS с открытым доступом.

**Comment by blackchestnut** [comment]
@Sfolt не понял тебя :)
помнишь мы как-то обсуждали некоторые проблемы по работе с апи:
Нельзя получить доступ по апи даже к публичным репозиториям без авторизации в гитхабе.
Поэтому при переходи на открытый борд идет проверка - автризирован ли пользователь в AS, если нет, то запоминаем что он хотел зайти наборд и отправляем его на главную (по хорошему сразу нужно предложить подключить приложение AS и авторизоваться через него, но пока так). После того как пользователь согласился происходит редирект на тот борд которых он хотел посмотреть.

> что значит «авторизированным в AS»?

Значит нажали Sign In with GitHub и согласились использовать наше приложение и создался пользователь в AgileSeason.

> По идее так как у Андрея не было доступа в наш сервис, он и не мог видеть его?

У него есть доступ, пользователь создан. Пока не было времени у него выяснить последовательность действий, которую он выполнял.

> Но он почему-то смог войти в борд AS.

Т.к. авторизовался - после этого увидел наш борд и создавал свой, ну или наоборот.

>  С другой стороны репозиторий AS с открытым доступом.

См. описание работы выше про особенности.

могу только предположить, что он вышел и попытался еще раз зайти на борд, а его просто кинуло на главную и он не понял, что произошло. При встрече уточню у него.

**Comment by DariaUlanova** [comment]
@blackchestnut да, нужно у Андрея уточнить, как я его поняла, у него был в какой-то момент доступ к борду AS со всеми тикетами, потом пропал.

Саш, а помнишь мы обсуждали про то, чтобы с сервисе можно было заводить пользователей (например, люди из производства), у которых не будет доступа к гитхабу, но будет доступ создавать тикеты и коментировать? Для этого будет достаточно через cancancan закрывать ссылки из интерфейса? Если так, то это не очень долго сделать, верно?

**Comment by blackchestnut** [comment]
@Sfolt нет это не так.
Дело в том, что нужен доступ к чтению из записи в репозиторий, а как мы уже с тобой обсуждали есть только один вариант пока - это сохранить чей-то github_token в базу и передать его другому человеку в рамках работы в AS.
К сожалению это очень большая дырка в безопасности, пусть даже мы и предупредим пользователей об этом и пусть даже они для этого дела выделят какого-нибудь "левого" пользователя "аватара" под кем будут все остальные работать - все равно даже одно сохранение этого токена в базу уже очень плохо! Т.к. если кто-то получит доступ к нашей базе - пиши пропала, будет утечка и кто-то сможет получить доступ к коду.

Даже копирование данных к нам не поможет, т.к. нужно комментировать и т.д. 

Если посмотришь, то сейчас он только в session[:github_token] храниться и изредка передается в другие функции только как параметр - и от этого нужно будет избавляться как-то, т.к. в sidekiq остаются параметры к таскам.

**Comment by blackchestnut** [comment]
Выяснил подробности - оказалось просто Андрей ожидал, что публичный борд у него останется. Есть идеи как немного переделать путь создания борда и расширить функционал boards#index #317
