### ISSUE TITLE
link to issue

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#300]
@blackchestnut Ты задачку делал с открытием тикета по урлу.

По урлу, например, `http://agileseason.com/boards/agileseason%2Fagileseason/issues/297` должен раскрыться попап с тикетом на фоне борда? Или это еще не сделано, а сделана только ссылка? 

У меня сейчас открывается голая паршал вьюха без лейаута и стилей. У меня что-то сломалось?

![2015-04-30 20 39 57](https://cloud.githubusercontent.com/assets/6046764/7418801/573dc1a0-ef79-11e4-8723-ceda96bf7168.png)

**Comment by Sfolt** [comment]
![uploads/4b0d209c-4781-46f4-bd47-4afdb1ea4edf/Снимок экрана 2015-04-15 в 21.22.58.png](https://agile-season-production.s3.amazonaws.com/uploads/4b0d209c-4781-46f4-bd47-4afdb1ea4edf/Снимок экрана 2015-04-15 в 21.22.58.png)

**Comment by blackchestnut** [comment]
@Sfolt, да сломалоь - на продакшене и у меня в dev работает. Открывается на фоне борда. Поищи `$ f issue-number`

**Comment by DariaUlanova** [comment]
ok
