### ISSUE TITLE
Comments order

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#301]
@blackchestnut часто ловлю себя на мысли, что порядок в трелло неудобный, а в гитхабе — то, что нужно, то есть сверху вниз от старого коммента к новому. Последовательность переписки бывает нужна, в трелло она инвертирована и потому иногда вводит в ступор. Что думаешь?

**Comment by Sfolt** [comment]
test

**Comment by blackchestnut** [comment]
@Sfolt,
Думаю, что если пользоваться чем-то одним, то привыкаешь. Но лично я туплю какое-то время когда переключаюсь между AS и Github-ом, т.к. она разная. Пожалуй с тобой соглашусь - лучше если будет совпадать с Github-ом.

**Comment by DariaUlanova** [comment]
ok
