### ISSUE TITLE
Error on my local maschine

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#310]

**Comment by DariaUlanova** [comment]
![uploads/7add4743-6c76-4dd9-b0f4-adaad277476c/Снимок экрана 2015-05-06 в 20.37.31.png](https://agile-season-production.s3.amazonaws.com/uploads/7add4743-6c76-4dd9-b0f4-adaad277476c/Снимок экрана 2015-05-06 в 20.37.31.png)

**Comment by DariaUlanova** [comment]
![2015-05-06 21 05 38](https://cloud.githubusercontent.com/assets/6046764/7500042/f43e2c4c-f433-11e4-9df9-211835bb1b88.png)

**Comment by DariaUlanova** [comment]
@blackchestnut еще у меня локально в мастере сайдкик взбесился: быстро, много и непрерывно что-то выводил, в итоге все упало с ошибкой ToManyRequests

В чем может быть проблема?

**Comment by blackchestnut** [comment]
@Sfolt,
дело в том, что у тебя долго не был включен сайдкик и куча тасков висели в редисе не выполненные, а после того как его включила наверное они все разом посыпались.

Подключу ограничение по количеству тасков для борда, возможно это решит проблему, пока можно зайти в `agileseason.dev/sidekiq` и убить все невыполненные таски и снова запустить сайдкик.

**Comment by blackchestnut** [comment]
Fix in 3119d5178da179898d414ea3e904d32765b7febc

**Comment by DariaUlanova** [comment]
@blackchestnut ошибка как на первом скриншоте осталась из-за @direct_post, 

```
.board [
    data-github_full_name="#{@board_bag.github_full_name}"
    data-direct_post_url="#{@direct_post.url}"
    data-direct_post_form_data="#{@direct_post.fields.to_json}"
  ]
```

**Comment by blackchestnut** [comment]
@Sfolt, ты добавляла:

```
ENV['AWS_ACCESS_KEY_ID'],
ENV['AWS_SECRET_ACCESS_KEY']
```

со значениями из письма которое я тебе присылал?

**Comment by DariaUlanova** [comment]
@blackchestnut  все ок, неправильно был назван этот файлик .env
