### ISSUE TITLE
File upload on local maschine

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#315]
@blackchestnut, видимо, в настройках амазона для загрузки файлов ты указывал кроме основного домена еще и agileseason.dev. Можно ли там указать localhost:3000 – у меня pow не работает.

**Comment by DariaUlanova** [comment]
![uploads/5ef6078b-11f0-47c2-a6c0-cc2bd3d243ec/Снимок экрана 2015-05-11 в 15.52.16.png](https://agile-season-production.s3.amazonaws.com/uploads%2F5ef6078b-11f0-47c2-a6c0-cc2bd3d243ec%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-05-11%20%D0%B2%2015.52.16.png)

**Comment by blackchestnut** [comment]
@Sfolt,
добавил, попробуй пожалуйста.

**Comment by DariaUlanova** [comment]
@blackchestnut спасибо, работает.
