### ISSUE TITLE
Tune Boards#index

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#317]
- [x] Redirect to Boards#index from menu
- [x] Add My boards list
- [x] Add Explore with public boards

**Comment by blackchestnut** [comment]
@Sfolt, пожалуйста сильно не пугайся зоны http://agileseason.com/boards
На ней я просто хотел решить несколько проблем. Во первых сделать ее разводящей для некоторых операций, а не долгую http://agileseason.com/repos, а так же куда-то добавить список публичных досок на подобие Explore у гитхаба и Explore public repos у кодклимата.

**Comment by DariaUlanova** [comment]
@blackchestnut да вроде ве ок)
