### ISSUE TITLE
Comments doesn't display after save if click on preview

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#320]

**Comment by blackchestnut** [comment]
Возможно preview не причем, т.к. иного комментарий не отображается и просто после сохранения - вот как сейчас :(.

**Comment by blackchestnut** [comment]
Хотя на тикете на борде сразу отображается иконка комментария

**Comment by blackchestnut** [comment]
еуые

**Comment by blackchestnut** [comment]
test

**Comment by blackchestnut** [comment]
Странно - заработало, хотя делал несколько раз cmd+shift+R для надежности, может из-за сети и связи с Github...

**Comment by blackchestnut** [comment]
Снова сломалось - видимо это плавающий баг.

**Comment by DariaUlanova** [comment]
ок

**Comment by Sfolt** [comment]
test

**Comment by Sfolt** [comment]
test test test

**Comment by Sfolt** [comment]
sdf sdf sd

**Comment by Sfolt** [comment]
sdsdfsdfgsd

**Comment by blackchestnut** [comment]
@Sfolt, а апи гитхаба случайно не возвращает комментарий в ответ на создание?

**Comment by blackchestnut** [comment]
У меня к стати не отобразился.

**Comment by Sfolt** [comment]
sflgddfg

**Comment by DariaUlanova** [comment]
@blackchestnut возвращает, но если по одному комменту загружать, то будет проблема с тем, что в DOMе не будет новодобавленных комментов, поэтому делаю перезагрузку всех комментариев и ставлю триггер после загрузки `comments:load`.

**Comment by Sfolt** [comment]
skhdf kdjshgf

**Comment by Sfolt** [comment]
sakdhf kasjdhfj askdfh

**Comment by Sfolt** [comment]
test

**Comment by Sfolt** [comment]
test 2

**Comment by Sfolt** [comment]
test 3

**Comment by Sfolt** [comment]
test

**Comment by blackchestnut** [comment]
@Sfolt я имел ввиду, что возможно можно после сохранения вставить сразу полученный комментарий от сервера в вертску.

**Comment by blackchestnut** [comment]
@Sfolt хотя помоему так и делается - покрайне мере визуально.

**Comment by DariaUlanova** [comment]
@blackchestnut так я тебя и поняла. Новодобавленный комментарий может быть изменен или удален. Для этого нужно каждый раз, кагда добавляется новый комментарий, навешивать события. Чтобы не плодить события, делаю перезагрузку всего списка комментариев. Думаешь, неудачное решение?

**Comment by DariaUlanova** [comment]
@blackchestnut еще я могу твой комментарий отредактировать, стоит ли закрывать доступ редактирования чужих комментов?

**Comment by blackchestnut** [comment]
@Sfolt, в гитхабе я то же могу отредактировать, но может это из-за прав на репозиторий... посмотри пожалуйста - можешь ли ты редактировать мои комменты в гитхабе? Если да, то можно оставить как есть.

**Comment by DariaUlanova** [comment]
@blackchestnut в гитхабе твои могу редактировать, значит все ок.
