### ISSUE TITLE
Don't remove empty lines in body and comments

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#322]

**Comment by DariaUlanova** [comment]
@blackchestnut не совсем поняла.

Ты про случай, если я в текстарки при редактировании несколько раз нажму enter, это создаст пустые строчки, и при сохранении они не удалятся, как в этом сообщении, а должны.

Об это идет речь?

**Comment by blackchestnut** [comment]
@Sfolt хм, не совсем тебя понял. Дело в том, что в разметке гитхаба пустой строкой отделяются новые строчки. Забыл накидать пример сразу, постараюсь сейчас вспомнить.

**Comment by blackchestnut** [comment]
вот такой текст:
![agile season 2015-05-17 20-52-56](https://cloud.githubusercontent.com/assets/2400100/7671395/bef7fed6-fcd6-11e4-9ff7-e82273ae2513.png)

в гитхабе:
![agileseason 2015-05-17 20-54-00](https://cloud.githubusercontent.com/assets/2400100/7671397/dff142d2-fcd6-11e4-9e6f-0ccc27de9541.png)

у нас сейчас:
![agile season 2015-05-17 20-54-45](https://cloud.githubusercontent.com/assets/2400100/7671398/fa111638-fcd6-11e4-952e-f7e112e800dc.png)

Это пример простой и тут не так страшно, но если что-то большое форматировать, то без этих отступов сложно понять.

**Comment by blackchestnut** [comment]
У нас то же все ок, если этот коммент не редактировать:
`line 1`
`line 2`

`line after empty line`

**Comment by DariaUlanova** [comment]
#322

@blackchestnut ok, еще бага с номером тикета, который переводится в заголовой (#322)

**Comment by blackchestnut** [comment]
`line 1`
`line 2`

`line after enter`

**Comment by blackchestnut** [comment]
новые линии из 
простого текста

после enter-а

**Comment by blackchestnut** [comment]
> fasdf

asdf
