### ISSUE TITLE
Github checkbox style

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#323]
- [ ] Not checked
- [x] Checked

VVVVVVVVVVVVV

![uploads/cc3f7907-6f92-4363-af81-23c8ce0a3d03/agileseason 2015-05-16 09-18-48.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fcc3f7907-6f92-4363-af81-23c8ce0a3d03%2Fagileseason%202015-05-16%2009-18-48.png)

**Comment by DariaUlanova** [comment]
- [ ] Not checked
- [x] Checked
