### ISSUE TITLE
Improve Drag and drop area

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#335]

**Comment by blackchestnut** [comment]
@Sfolt, уже 3-й раз заметил за собой такой фэйл:
- вырезаю скриншот
- открываю тикет в попапе
- сразу перетаскиваю картинку

![uploads/bffce56b-fbe4-4d73-8be8-5d19ad696401/Agile Season 2015-05-20 07-31-09.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fbffce56b-fbe4-4d73-8be8-5d19ad696401%2FAgile%20Season%202015-05-20%2007-31-09.png)

Дело в том, что в гитхабе сразу открыт коммент и в него могу бросить картинку и это уже видимо в мозгу и никак не могу переучиться, чтобы в нашем тиките сначала кликнуть в потом перетащить.

@Sfolt, были ли у тебя похожие ситуации? Можем ли мы как-то отследить, что пытаются перетащить картинку на комментарий и например раскрыть поле ввода?

**Comment by DariaUlanova** [comment]
@blackchestnut да, скорее всего при наведении на коммент, он должен раскрываться, и когда дропаешь, то дроп срабатывает на обычной текстарии.

**Comment by DariaUlanova** [comment]
test

``` ryby
class MyClass
  def initialize(name)
    @name = name
  end

  def name
    @name
  end
end
```
