### ISSUE TITLE
Add data-disable-with="text..." to buttons

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#351]
Try https://github.com/eploko/simple_form-magic_submit with locales

**Comment by blackchestnut** [comment]
Если не использовать `simple_form` то можно просто,
`data: { disable_with: 'Сохранение...' }`

**Comment by blackchestnut** [comment]
@Sfolt, видел по коммитам ты эту вещь то же захватила.

**Comment by DariaUlanova** [comment]
Еще не ко всем кнопкам добавлено, тут еще будут правки.

**Comment by blackchestnut** [comment]
@Sfolt, Возможно стоит в этом issue ограничиться только issue#show и 2-мя кнопочками на миниатюре issue. Это основые действия. А то очень муторно и долго получится. Остальное можно заменять по мере проблем или времени.

**Comment by Sfolt** [comment]
test
