### ISSUE TITLE
Github markup with code highlighting has broken 

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#354]

**Comment by DariaUlanova** [comment]
![uploads/a21946cd-6b57-46b9-8e61-76cfddba42f9/Снимок экрана 2015-05-31 в 14.05.23.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fa21946cd-6b57-46b9-8e61-76cfddba42f9%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-05-31%20%D0%B2%2014.05.23.png)
![uploads/a21946cd-6b57-46b9-8e61-76cfddba42f9/Снимок экрана 2015-05-31 в 14.05.59.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fa21946cd-6b57-46b9-8e61-76cfddba42f9%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-05-31%20%D0%B2%2014.05.59.png)

**Comment by DariaUlanova** [comment]
@blackchestnut it is because of this

```
  def fix_new_line(text)
    text.gsub("\n", '<br />')
  end
```

application_helper.rb

![uploads/746b9fae-356b-459b-acd4-7ae6cb503eb4/Снимок экрана 2015-05-31 в 18.57.04.png](https://agile-season-production.s3.amazonaws.com/uploads%2F746b9fae-356b-459b-acd4-7ae6cb503eb4%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-05-31%20%D0%B2%2018.57.04.png)

**Comment by blackchestnut** [comment]
@Sfolt, пытался починить http://agileseason.com/boards/agileseason%2Fagileseason#issue-number=322 #322 

похоже сделал криво.

**Comment by DariaUlanova** [comment]
@blackchestnut в геме redcarpet есть опция:

> :hard_wrap: insert HTML <br> tags inside on paragraphs where the origin Markdown document had newlines (by default, Markdown ignores these newlines).
