### ISSUE TITLE
Tune main menu

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#357]
- [x] Make menu elements easy to click
- [x] Links behavior shouldn't change 
- [x] One boards page instead two (repos & boards)

**Comment by DariaUlanova** [comment]
- [x] Цвет фона #ffe57f или #ffecb3
- [x] иконка "черточек" левого меню "скачет" при закрытом и открытом дажборде. 
- [x] Ссылка настроек, тоже немного двигается.
- [x] Выделяется выбранный элемент более темным background-ом только название борда (возможно это пример, если так, то нравится с выделением области, а не только светом текста, как в settings).
- [x] На второстепенных страничках с описанием по графикам не открывается левое меню.

**Comment by blackchestnut** [comment]
Изменение wip при превышении или недоборе.

**Comment by blackchestnut** [comment]
@Sfolt помоему только что поехало:
![agile season 2015-06-29 22-55-48](https://cloud.githubusercontent.com/assets/2400100/8416978/1869d6ea-1eb2-11e5-9396-9a12510fdaef.png)

**Comment by blackchestnut** [comment]
@Sfolt ага, в моей ветке нету, похоже "лупа" немного смещается.

**Comment by DariaUlanova** [comment]
@blackchestnut ok

**Comment by blackchestnut** [comment]
так же заметил, что под ней результаты поиска "спрятались"

**Comment by DariaUlanova** [comment]
@blackchestnut поле и результаты поиска поправила
