### ISSUE TITLE
Error on local maschine every time after reloading page or coming to another page.

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#366]
Description![uploads/730f3862-5af0-484a-8b28-356e7bd31f6d/Снимок экрана 2015-06-04 в 22.39.28.png](https://agile-season-production.s3.amazonaws.com/uploads%2F730f3862-5af0-484a-8b28-356e7bd31f6d%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-06-04%20%D0%B2%2022.39.28.png)

**Comment by Sfolt** [comment]
Scheiße, опять верстку сломала(

**Comment by DariaUlanova** [comment]
@blackchestnut when reloading rails server AS works. But after reloading it raises this error

**Comment by DariaUlanova** [comment]
What's may be the reason of the error?

**Comment by DariaUlanova** [comment]
And the error appears on all pages

**Comment by DariaUlanova** [comment]
mine fault :)

**Comment by blackchestnut** [comment]
ok :)
