### ISSUE TITLE
Drag and drop remove body text

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#369]

**Comment by blackchestnut** [comment]
wait #377, #430

**Comment by blackchestnut** [comment]
wait #430

**Comment by DariaUlanova** [comment]
test
![uploads/f16f32eb-a77f-4670-a82c-3dd5e748b63f/Снимок экрана 2015-05-31 в 18.57.04.png](https://agile-season-production.s3.amazonaws.com/uploads%2Ff16f32eb-a77f-4670-a82c-3dd5e748b63f%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-05-31%20%D0%B2%2018.57.04.png)
