### ISSUE TITLE
Add custom font colors for standart github labels

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#388]

**Comment by blackchestnut** [comment]
![agile season 2015-06-11 13-18-25](https://cloud.githubusercontent.com/assets/2400100/8104835/a9f86704-103c-11e5-8d7a-04e8f12e6b53.png)

**Comment by blackchestnut** [comment]
Теперь у нас добавление так:

**Comment by blackchestnut** [comment]
Теперь у нас добавление так:
![uploads/50b758ba-da70-40a6-8300-336c4ff12a72/Agile Season 2015-07-13 06-53-55.png](https://agile-season-production.s3.amazonaws.com/uploads%2F50b758ba-da70-40a6-8300-336c4ff12a72%2FAgile%20Season%202015-07-13%2006-53-55.png)

**Comment by blackchestnut** [comment]
Возможно в таком варианте вообще нет смысла изменять цвет текста. @Sfolt, что думаешь?

**Comment by blackchestnut** [comment]
@Sfolt, нужно ли сделать черными цвета и на тикетах? Или же все таки там будет в зависимости от цвета фона?

**Comment by DariaUlanova** [comment]
@blackchestnut, не, хочется либо захардкодить для стандартных цветов гитхаба цвета текста, либо дописать твой скрипт определения цвета. На скриншоте, красные и особенно зеленый при меньшем размере трудно читать.

**Comment by blackchestnut** [comment]
@Sfolt ок, захордкодим как в гитхабе.

**Comment by DariaUlanova** [comment]
@blackchestnut ok
