### ISSUE TITLE
Sort bugs from Andrey

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#389]
Перевод issue в архив перезагружает страницу (из модального окна редактирования issue)

Попап выбора labels, assignee не ведёт себя как модальное окно. Не исчезает по клику вне попапа
В ".description p" у issue предлагаю поставить line-height: 1.65em
margin-bottom: 5px

Сильно не хватает тянущегося по высоте textarea для issue description. Плагин для этого http://www.unwrongest.com/projects/elastic/

Если после редактирования промахнулся по save, то весь текст теряется

cmd+enter не сохраняет текст issue
esc не отменяет редактирование текста

Редактирование заголовка issue должно быть input type=text, а не textarea
enter не сохраняет отредактированный заголовок issue
esc не отменяет редактирование заголовка issue

Не работает редактирование колонок http://take.ms/Bs7R6

Закрытый issue нельзя повторно открыть

Перевод задачи в архив не уменьшает цифру в колонке http://take.ms/5UC6A

**Comment by morr** [comment]
@blackchestnut ещё сломались галочки в описании issue
так же line-height: 1.65 и для textarea стоит выставить

![monosnap 2015-06-12 00-49-22](https://cloud.githubusercontent.com/assets/134610/8119298/3046aab8-109d-11e5-8aff-440327d17a8d.png)

**Comment by blackchestnut** [comment]
создал тикеты
