### ISSUE TITLE
Archive via ajax

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#391]

**Comment by DariaUlanova** [comment]
@blackchestnut я подумала, что после закрытия и отправки в архив больше нет смысла что-то делать с тикетом, поэтому нужно по клику на эти кнопки вернуться на борд. Как ты считаешь?

**Comment by blackchestnut** [comment]
@Sfolt тут нужно подумать - а что если я случайно клинул... и хочу сразу вернуть обратно? То же самое и по закрытию. То что сейчас на борд кидает думаю не совсем верно.

P.S. Если все же решим делать, то хорошо бы так же решить - нужно ли как-то визуализировать, что issue закрытый и архивный на issues#show? Актуально когда я отрываю по поиску или из activities старый issue.

**Comment by DariaUlanova** [comment]
@blackchestnut

Вижу два варианта.
1. Закрывать аяксом, и тикет помечается как закрытый/в архиве. Этот вариант упирается в задачу Restore from archive #392 (+ restore from closed).
2. Кнопка ведет себя как кнопка удаления, значит нужно добавить алерт с подтверждением.

Первый вариант мне нравится больше.

Согласна, что нужно как-то помечать закрытый тикет.

**Comment by blackchestnut** [comment]
@Sfolt, а мне алерты меньше нравятся... страшного же ничего не будет если я потом восстановлю.

**Comment by DariaUlanova** [comment]
@blackchestnut согласна
