### ISSUE TITLE
Add Elastic for description and comments

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#395]
http://www.unwrongest.com/projects/elastic/

**Comment by blackchestnut** [comment]
Try line-height: 1.65em margin-bottom: 5px for ".description p" (issue) and textarea

**Comment by blackchestnut** [comment]
sdfasdfasdfa

**Comment by blackchestnut** [comment]
asdfasdf

**Comment by blackchestnut** [comment]
asdfasdf

**Comment by blackchestnut** [comment]
565656

**Comment by blackchestnut** [comment]
- [x] wait #377

**Comment by DariaUlanova** [comment]
- [x] Прыгает при сохранении, надо поправить еще.

**Comment by DariaUlanova** [comment]
![uploads/683a5d5a-391e-49a2-b5f5-e003df0e4e33/Снимок экрана 2015-07-05 в 14.55.57.png](https://agile-season-production.s3.amazonaws.com/uploads%2F683a5d5a-391e-49a2-b5f5-e003df0e4e33%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-07-05%20%D0%B2%2014.55.57.png)

**Comment by DariaUlanova** [comment]
Oops

**Comment by blackchestnut** [comment]
![uploads/122a3266-a848-4c5d-a9c8-7b48e9e59493/Agile Season 2015-07-05 14-58-31.png](https://agile-season-production.s3.amazonaws.com/uploads%2F122a3266-a848-4c5d-a9c8-7b48e9e59493%2FAgile%20Season%202015-07-05%2014-58-31.png)

**Comment by blackchestnut** [comment]
@Sfolt
![uploads/122a3266-a848-4c5d-a9c8-7b48e9e59493/Agile Season 2015-07-05 14-59-27.png](https://agile-season-production.s3.amazonaws.com/uploads%2F122a3266-a848-4c5d-a9c8-7b48e9e59493%2FAgile%20Season%202015-07-05%2014-59-27.png)

**Comment by blackchestnut** [comment]
test
test
set

**Comment by blackchestnut** [comment]
@Sfolt, на текущий момент обновление заголовка произойдет по onblur, но при редактировании это не очевидно, плюс не видно где заканчивается textarea. Хотя, если cmd+enter (или ctr+enter для винды) исправит ситуацию. Еще вопрос для размышления - может для заголовка нам заканчивать редактирование по enter?

**Comment by DariaUlanova** [comment]
@blackchestnut Поле заголовка, на мой взгляд, можно сохранять сразу, это не сложный комментарий со вставкой кода и картинки. Обычно заголовок пишется быстро и, как правило, не редактируется. Поэтому такое «быстрое» поле нужно избавить от лишних шагов типа клика по кнопке.
