### ISSUE TITLE
Нужно ли описание тикета, не смотря на то, что в гитхабе оно есть? Часто ли ты записываешь что-нибудь в гитхабе в описание вместо комментария? Комментарии идут по хронологии с ранних записей сверху вниз к новым, поэтому при создании тикета, первый комментарий на видном месте.

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#420]

**Comment by blackchestnut** [comment]
@Sfolt, очень интересная мысль!
Если судить по себе, то я в трелло и гитхабе нарочно пишу в комментарий а не в описание, для того, чтобы остался мой аватар и было понятно кто пишет. А в AgileSeason последнее время совсем не использую описание. Может попробовать убрать и посмотреть что будет?

**Comment by blackchestnut** [comment]
Единственное, что может помешать, так это то что комментарий можно удалить, а при удалении текста в описании остается дата и имя того кто изменил описание, но это возможно надуманно и не особо важно. Так что я за то, чтобы попробовать без описания.

**Comment by blackchestnut** [comment]
Если что всегда можно вернуть.

**Comment by DariaUlanova** [comment]
@blackchestnut ok, уберем. Вернем, если нужно будет.
