### ISSUE TITLE
File uploading by drag & drop is broken

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#430]

**Comment by blackchestnut** [comment]
Может поможет, картинка в #433

**Comment by DariaUlanova** [comment]
- [x] починить загрузку драг-н-дроппом
- [x] починить стили драг-н-дропа
- [x] починить загрузку по ссылке
- [x] проверить, не плодятся ли вызовы функции загрузки при переходе по страницам

**Comment by blackchestnut** [comment]
![uploads/e15a0cf3-fd30-4883-a51f-61eaae72aa7e/Agile Season 2015-07-05 06-22-08.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fe15a0cf3\-fd30\-4883\-a51f\-61eaae72aa7e%2FAgile%20Season%202015\-07\-05%2006\-22\-08\.png)
