### ISSUE TITLE
Bug in assigned users

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#432]

**Comment by blackchestnut** [comment]
![agile season 2015-06-26 05-52-07](https://cloud.githubusercontent.com/assets/2400100/8369786/934a7132-1bc7-11e5-9154-05c5afe949b4.png)

**Comment by DariaUlanova** [comment]
На продакшене не отмечается галкой, выбранный пользователь, то есть не выполнятеся условие во вьюхе

```
span.check class="#{'octicon octicon-check' if user.id == issue.assignee.try(:id)}"
```

хотя в гитхабе пользователь также выбран. И в интерфейсе АС иконка выбранного пользователя присутствует. 

Локально галка появляется.

![uploads/e7c7f717-24cb-46a1-8679-687547ea37a1/Снимок экрана 2015-07-07 в 19.20.24.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fe7c7f717-24cb-46a1-8679-687547ea37a1%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-07-07%20%D0%B2%2019.20.24.png)

**Comment by DariaUlanova** [comment]
@blackchestnut,

проверка по id не работает на продакшене, а локально работает. Как думаешь, почму так?

проверка по логину работает

```
if user.login == issue.assignee.try(:login)
```
