### ISSUE TITLE
Remove br from checkoxes in comments

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#437]

**Comment by blackchestnut** [comment]
Test:
- [x] ch-1
- [ ] ch-2

**Comment by blackchestnut** [comment]
![agile season 2015-06-26 07-09-55](https://cloud.githubusercontent.com/assets/2400100/8370601/9fe3c29e-1bd2-11e5-9ea9-f527641e909f.png)

**Comment by DariaUlanova** [comment]
- [ ] Сделать возможность сохранять пустые строчки как в гитхабе, но так, чтобы они не ломали верстку кода.

Сейчас строчки комментариев слипаются в кучу

![uploads/3048baf3-7876-407d-85fe-e3a052e953f4/Снимок экрана 2015-07-07 в 20.00.58.png](https://agile-season-production.s3.amazonaws.com/uploads%2F3048baf3-7876-407d-85fe-e3a052e953f4%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-07-07%20%D0%B2%2020.00.58.png)
