### ISSUE TITLE
No redirect to boards#show by one click after save due date.

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#439]

**Comment by blackchestnut** [comment]
На issues#show после сохранения даты приходится 2а раза кликать в меню, чтобы вернуло на борд. Esc работает нормально. Возможно там остается какой-нибудь overlay.

**Comment by blackchestnut** [comment]
Тоже самое и при назначении пользователя.

**Comment by DariaUlanova** [comment]
@blackchestnut, да, там оверлей, чтобы закрывать по клику мимо попапа. По крестику не удобно — он мелкий. Можно убрать оверлей. Скрывать попап повторно, кликнув на кнопку. Кнопку с раскрытым тултипом выделить другим цветом (оранжевым).

**Comment by blackchestnut** [comment]
@Sfolt не понял, может мы про разные вещи?

**Comment by DariaUlanova** [comment]
![uploads/5ac68320-5ec8-4f3d-8847-bb3f6f7ea168/Снимок экрана 2015-07-22 в 22.39.58.png](https://agile-season-production.s3.amazonaws.com/uploads%2F5ac68320-5ec8-4f3d-8847-bb3f6f7ea168%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-07-22%20%D0%B2%2022.39.58.png)

**Comment by DariaUlanova** [comment]
@blackchestnut, как я поняла, про попап с календарем.

**Comment by blackchestnut** [comment]
@Sfolt да про него, но только я имел введу не совсем это (возможно). То что он скрывается по оверлею это хорошо, нужно просто придумать как возвращаться на борд по одному клику в мею.  Чтобы не закрывать сначал календарь или назначенных. А то у меня уже привычка выработалась 2а раза кликать машинально всегда :) Возможно его можно меньше сделать, чтобы он не заходил на меню, либо как-то еще определить, что курсор кликает в меню и значит нужно сразу на борд возвращаться.

**Comment by DariaUlanova** [comment]
@blackchestnut ok, поняла, да можно так сделать
