### ISSUE TITLE
Check sort_issues with archived and restored

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#448]

**Comment by blackchestnut** [comment]
Есть предположение, что не отображаются тикеты в последней колонке, если их нет в массиве сортировки (у колонки).

**Comment by blackchestnut** [comment]
нет - просто в самом низу оказываются.

**Comment by DariaUlanova** [comment]
@blackchestnut, видимо, потому что они обычно переносятся в последнюю колонку на странице тикета.

**Comment by blackchestnut** [comment]
@Sfolt нет, это не так. На странице тикета я делал, чтобы в начало падали - в конец не удобно. А то что при отсутствии в массиве issues попадает в конец - это не важно, ну и пусть.

**Comment by DariaUlanova** [comment]
@blackchestnut ok
