### ISSUE TITLE
Comments multiply when being created after going through the history. Try change event 'page:change' on smth like 'page:load' 

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#473]

**Comment by blackchestnut** [comment]
так же дублируются confirm-ы, по 2а на каждое удаление.

**Comment by blackchestnut** [comment]
test

**Comment by blackchestnut** [comment]
![uploads/3b2fffee-63bc-436d-ad3e-e3775cdb3f75/Agile Season 2015-07-05 07-56-41.png](https://agile-season-production.s3.amazonaws.com/uploads%2F3b2fffee\-63bc\-436d\-ad3e\-e3775cdb3f75%2FAgile%20Season%202015\-07\-05%2007\-56\-41\.png)

**Comment by DariaUlanova** [comment]
test

**Comment by DariaUlanova** [comment]
test2

**Comment by DariaUlanova** [comment]
test3

**Comment by DariaUlanova** [comment]
@blackchestnut `$(document).on 'ready page:load'` сработало, комментари больше не плодятся.
