### ISSUE TITLE
Sometimes creating a new issue is broken

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#474]

**Comment by DariaUlanova** [comment]
It is possible to add a new issue only after page reload.

**Comment by blackchestnut** [comment]
@Sfolt, видимо алгоритм воспроизведение немного хитрее - не смог повторить. У тебя это локально воспроизводится?

**Comment by DariaUlanova** [comment]
@blackchestnut не воспроизводится. Кажется воспроизводилось на продакшене.

**Comment by DariaUlanova** [comment]
@blackchestnut На продакшене пока не воспроизводится. Может эта бага появляется после обновления борда с помощью фэя?

**Comment by blackchestnut** [comment]
@Sfolt, борд пока не обновляется, только признак отправляется, что кто-то переместил тикет. Давай посмотрим, может еще воспроизведется.

**Comment by DariaUlanova** [comment]
@blackchestnut воспроизводится, если долго не обновляешь страницу. Добавить новый тикет не получается.![uploads/32cf257a-6b41-4885-a383-7ea69fc32afa/Снимок экрана 2015-07-07 в 16.55.30.png](https://agile-season-production.s3.amazonaws.com/uploads%2F32cf257a-6b41-4885-a383-7ea69fc32afa%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-07-07%20%D0%B2%2016.55.30.png)

**Comment by blackchestnut** [comment]
@Sfolt, понял, спасибо за скрин - буду смотреть.

**Comment by blackchestnut** [comment]
@Sfolt, не получается воспроизвести локально. Воспроизвожу закрытие соединения - тикет все равно добавляется. Отрубаю faye вообще, что сразу не удается подсоединиться... консоль вся красная, а тикеты добавляются.

**Comment by DariaUlanova** [comment]
@blackchestnut не знаю, сколько времени нужно ждать, но обычно получалось воспроизвести эту багу так: оставляешь на несколько часов открытый борд, потом пытаешься добавить тикет, и он не добавляется.

**Comment by blackchestnut** [comment]
Нашел правильную ошибку, пока не понятно как воспроизвести:

![uploads/dcd0b3ab-eb1f-4978-a8ee-cce3bdf9c7b7/pumba...” 2015-07-14 10-37-06.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fdcd0b3ab-eb1f-4978-a8ee-cce3bdf9c7b7%2Fpumba...%E2%80%9D%202015-07-14%2010-37-06.png)

**Comment by blackchestnut** [comment]
@Sfolt, есть идеи что это за onloadwff?

**Comment by blackchestnut** [comment]
@Sfolt, если до 1.09 бага не будет воспроизводится, то закроем тикет.

**Comment by blackchestnut** [comment]
@Sfolt, вроде бы воспроизводиться начала крайне редко. Если снова начем ловить то откроем заного.

**Comment by DariaUlanova** [comment]
@blackchestnut ok
