### ISSUE TITLE
Beautiful Landing

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#510]

**Comment by blackchestnut** [comment]
- [x] what is it? (in 5 words)
- [x] short answer - why agile season?
- [ ] simple feature list
- [x] prices (private - $4 by repo, public - free forever)
- [x] link to github repo
- [ ] badge "early access"
- [x] links to privacy, security and terms

**Comment by blackchestnut** [comment]
@Sfolt, нужна помощь с главной :)

**Comment by Sfolt** [comment]
@blackchestnut, первый набросок текста для лендинга https://docs.google.com/document/d/158erxNMpKpLaz6MFcZ-ug8w7IJOKzli2Lwo3yI2g9WQ/edit?usp=sharing

**Comment by DariaUlanova** [comment]
@blackchestnut перенесла документ с текстом в общую папку https://docs.google.com/document/d/1CdlC6IvSYnCO_mWPk1okotzMZG2rK6GA4fQZC4ZmT1o/edit

Старый удалила.

Переработанный текст https://drive.google.com/drive/folders/0B2gyiD702Cz_fkVhaGJmYmlTMXczNWpXWXNvLXM4UndfNF9WMWRGTmJCYUQ1S3NTalNrNXM

**Comment by DariaUlanova** [comment]
@blackchestnut 
Хочется при встрече обсудить некоторые вопросы.

Какие основные фичи АС? 
1. Гитхаб-задачи на канбан-доске.
2. Сбор и отображение статистики.

Как эти основные фичи перевести на язык пользователя?
1. Гитхаб-задачи на канбан-доске. (единое рабочее пространство команды)
2. Сбор и отображение статистики. (1. Прогноз сроков проекта, 2. Стимулирование команды работать быстрее)

Как по-твоему?

**Comment by DariaUlanova** [comment]
Какие основные показатели дает каждый из графиков?

Cumulative flow
1. Work in progress
2. Cycle time for the interval
- reveal bottlenecks

Control chart
1. Cycle time for eacj issue
Как время цикла распределено по конкретным задачам

**Comment by blackchestnut** [comment]
> Какие основные показатели дает каждый из графиков?

Control chart - Cycle time. То что там есть еще среднее и скользящее среднее это уже дополнительная инфа, главное это время цикла по каждой задачи. Основная задача канбан-команды это уменьшение cycle time.

Frequency - распределение задач по длительности т.е. помогает узнать сколько у тебя каких задач и ориентирует по производительности команды.

**Comment by blackchestnut** [comment]
> Какие основные фичи АС?

чем короче тем лучше :) основная идея - "аджайл борд со статистикой по тикетам из гитхаба". Не угадать какие фичи будут главные. Мне например уже больше по душе то как выглядит борд и просто в нем приятно тикеты перетаскивать, хотя раньше думал, что стата это главное. Не думай больше 20 мин. :)

**Comment by blackchestnut** [comment]
> Стимулирование команды работать быстрее

Давай лучше
- Помогает измерить влияние изменений в процессе на производительность команды.
- Более точно прогнозировать дату завершения проекта.
- Использовать статистику из прошлого периода, чтобы ставить новые цели для команды.

P.S. Последние годы с осторожностью отношусь к словам "работать быстрее" :)

**Comment by DariaUlanova** [comment]
@blackchestnut https://drive.google.com/file/d/0B-sdZHXk6gN8bGN5XzR6SkJXMlE/view

**Comment by blackchestnut** [comment]
@Sfolt мне нравится, а как скринкаст снять? :)

**Comment by blackchestnut** [comment]
Единственный момент я бы про экономию убрал, т.к. на этой странице человек пока не принимает решение растататься с деньгами поэтому инфа по скидке при оплате 6ть месяцев может ему не очем не говорить - он еще скорее всего не принял решения пользоваться, поэтому эта выгода для него не нужна.

**Comment by DariaUlanova** [comment]
@blackchestnut

> как скринкаст снять?

Например, с моноснап, легко делается. Правда я задумала сделать немного замороченный скринкаст, и, пожалуй это будет не видео, а гифка, но посмотрю по размеру файла.

> я бы про экономию убрал.

Предлагаешь оставить только 4$ и free на этой странице?

**Comment by blackchestnut** [comment]
> Предлагаешь оставить только 4$ и free на этой странице?

Да, я бы оставил только их. Дополнительно когда разберемся с привязкой карты, то скидка тоже будет не актуальна.

**Comment by blackchestnut** [comment]
@Sfolt, похоже у тебя на лендинге нет jquery:
![uploads/2015-08-11_5eb6cbf5-e7db-407e-a0ee-cc8f63fe377c/Agile Season 2015-08-11 22-26-56.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-11_5eb6cbf5-e7db-407e-a0ee-cc8f63fe377c%2FAgile%20Season%202015-08-11%2022-26-56.png)

**Comment by blackchestnut** [comment]
@Sfolt, jquery пофиксил тут https://github.com/agileseason/agileseason/pull/592/files

**Comment by blackchestnut** [comment]
@Sfolt, раньше шрифт был прикольнее :)
![uploads/2015-08-12_ea5d68e0-f406-4f4a-a75d-9049dcbecce5/Agile Season 2015-08-12 09-29-06.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-12_ea5d68e0-f406-4f4a-a75d-9049dcbecce5%2FAgile%20Season%202015-08-12%2009-29-06.png)

**Comment by DariaUlanova** [comment]
@blackchestnut на скриншоте комик санс)

**Comment by blackchestnut** [comment]
@Sfolt из последних тестов в обзаце про Control Chart

> rolling average deviation

Не уверен в англиском, но возможно слово deviation лишнее. Возможно оно используется в словосочетании medium square deviation, а этого у нас пока нет.

Может лучше добавить в название 

> Cumulative flow

в конце Diagram т.к. уже устоявшееся название и сокращение CFD, а то получается у Control-а есть приписка что это Chart, а тут нет.

**Comment by blackchestnut** [comment]
@Sfolt,

> на скриншоте комик санс)

в общем хотел сказать, что с такими закорючками лучше :)

![uploads/2015-08-14_4bec4f74-fcb3-4cb2-932a-7444ad037014/Agile Season 2015-08-14 08-30-12.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-14_4bec4f74-fcb3-4cb2-932a-7444ad037014%2FAgile%20Season%202015-08-14%2008-30-12.png)

:+1:

**Comment by blackchestnut** [comment]
@Sfolt понравилось, что убрала цену в текст - возможно большие блоки с ценами где всего по сути 2е позиции лишнее

**Comment by DariaUlanova** [comment]
@blackchestnut deviation относилось к другому слову, которое я удалила.
