### ISSUE TITLE
First 100 users

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#512]

**Comment by blackchestnut** [comment]
wait #510

**Comment by blackchestnut** [comment]
@Sfolt, рекламную кампанию создал, показы пошли, ждем новых пользователей.
Пока заходил только один из индии, но борд не создал.

**Comment by blackchestnut** [comment]
Вообще получается, что все очень дорого, особенно из штатов - клик до 400 рублей доходит! по нашим запросам.
Добавил таргетинг:
Целевые местоположения:
Австралия (страна)
Бразилия (страна)
Канада (страна)
Греция (страна)
Индия (страна)
Россия (страна)
Великобритания (страна)
Соединенные Штаты Америки (страна)

**Comment by blackchestnut** [comment]
@Sfolt, нашел несколько площадок, где можно в комментариях про нас упомянуть - может удасться пообщаться на тему обзора. В общем если будут идеи то же пиши.

**Comment by blackchestnut** [comment]
@Sfolt, у меня еще есть на примете несколько человек с командами кому можно будет написать - подожду твоего лендинга, не горит, но их только 2а :(

**Comment by blackchestnut** [comment]
@Sfolt, в общем было 4и перехода, 1 регистрация и 500 рублей кончились :) Не знаю были такие же проблемы у пользователей при регистрации как уменя в #591. Отпишу знакомым, если у них ОС критичной не будет, то запущу еще немного.

**Comment by DariaUlanova** [comment]
@blackchestnut по каким запросам такие цены? 

У меня есть пара полузнакомых полуруби полупрограммистов, попробую подкатить)

**Comment by blackchestnut** [comment]
> по каким запросам такие цены?

@Sfolt,
![uploads/2015-08-16_1167f674-bd4a-4a87-a10d-fdf7c30499e3/Управление кампаниями – Google AdWords 2015-08-16 23-29-02.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-16_1167f674-bd4a-4a87-a10d-fdf7c30499e3%2F%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BA%D0%B0%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8%C2%A0%E2%80%93%20Google%20AdWords%202015-08-16%2023-29-02.png)

**Comment by blackchestnut** [comment]
Пробовал писать более низкочастотные запросы, но гугл отказывался их показывать - говорил, что нет аудитории. Сейчас добавил стран побольше: бразилию, индию, австралию, англию вроде удалось немного скинуть стоимость - некоторые показывается и по 50 рублей за клик.

**Comment by DariaUlanova** [comment]
@blackchestnut ok

**Comment by blackchestnut** [comment]
@Sfolt, запустил еще немного через гугл

**Comment by blackchestnut** [comment]
Через google похоже столько быстро не привести, покрайне мере за не очень большие деньги.
