### ISSUE TITLE
Link#N in comments - open issue

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#513]

**Comment by blackchestnut** [comment]
test #513

**Comment by DariaUlanova** [comment]
@blackchestnut, на борде ссылки с решеткой ведут на гитхаб, а тут, на странице тикета, — на тикет, это плохо. Может при сохранении ссылка автоматически должна подставлять текстовую ссылку (название тикета), которая подставится перед ссылкой с решеткой?

**Comment by blackchestnut** [comment]
@Sfolt то, что по разному, да не хорошо, но как-то нужно сделать чтобы было одинаково и удобно, везде переходить на гитхаб не надо, плюс у нас еще есть активности в которых то же ссылки. Если что-то писать вариант, но только что? Да и еще не очень длинное.

**Comment by blackchestnut** [comment]
@Sfolt хотя на самом деле мне понятно, что если я нахожусь на тикете с номером 1 и кликаю по #1 то уйду в гитхаб, а если я нахожусь на 1 и кликаю по #2 то это ссылка на другой тикет.
