### ISSUE TITLE
How we can accelerate issues#show?

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#537]

**Comment by blackchestnut** [comment]
За время работы начал за собой замечать, что появляются идеи добавления разного функционала связанного с тикетом сразу на борд - коренвой причиной этого думаю то, что из-за медленного открытия тикета (подсознательно не хочется иногда его открывать). Хоть он и стал чуть быстрее открываться, но это не достаточно быстро.

Есть предложение попробовать сделать следующее: в тикете есть поле с количеством комментариев - что если нам заранее при открытии показывать все блоки с комментариями, но еще пустыми (можно даже аватарку размыть и время, ну или как-то стилистически показать что там скоро будут данные), я помоему так видел где-то, а потом как аякс с данными придет, то вставить туда данные.

Вспомнил где видел - в фейсбучном приложении на айфоне и в хуборде.

Что думаешь?

**Comment by blackchestnut** [comment]
@Sfolt, еще как вариант быстро фикса сейчас можно добавить условие, что если число комментариев 0 в кэше тикета, то не делать загузку (но это только временное решение и поможет тольок для тех у кого комментов нет).

**Comment by blackchestnut** [comment]
- [ ] xh

**Comment by DariaUlanova** [comment]
@blackchestnut, ок, соглашусь, полезная фича.

**Comment by DariaUlanova** [comment]
Когда снова захотим вернуть открытие тикета без перезагрузки страницы, комментарии  будут отдельно подгружаться с задержкой, и пока они подгружаются, можно выводить схематичные блоки комментариев.

**Comment by blackchestnut** [comment]
Возможно стоит ради эксперимента попробовать и на текущей реализации, т.к. часто заходишь на тикет, чтобы поправить лейбел или назначить кого-то... хотя насколько критично будет, если у нас описание всегда в комментарии - в общем хочется попробовать, но это так - тюнинг.
