### ISSUE TITLE
Make board background and cards more contrast

### ISSUE THREAD

**Issue by hbda** [agileseason/agileseason-v1#563]

**Comment by blackchestnut** [comment]
Задачка от @hbda нужно посмотреть как на его мониторе смотрится. У меня на маке все ок.

**Comment by blackchestnut** [comment]
нужно будет собрать статистику на пользователях - что у них за техника используется.
@Sfolt, на моем рабочем ноуте картинка действительно не сильно контрастная, но мне не хочется основываться на том как это выглядит на нищебродских ноутах.

**Comment by hbda** [comment]
@blackchestnut Может тогда дать возможность пользователям поменять цвет фона? Не у всех же маки и супер мониторы.

**Comment by blackchestnut** [comment]
Added feature color-picker #609 in our backlog
