### ISSUE TITLE
prettify stylesheets for subscriptions#new

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#565]

**Comment by blackchestnut** [comment]
![uploads/d991c2b4-d2b1-49c6-bac6-00c93b465e46/Agile Season 2015-08-06 09-34-36.png](https://agile-season-production.s3.amazonaws.com/uploads%2Fd991c2b4-d2b1-49c6-bac6-00c93b465e46%2FAgile%20Season%202015-08-06%2009-34-36.png)

**Comment by DariaUlanova** [comment]
@blackchestnut что значит save 16%?

**Comment by blackchestnut** [comment]
> что значит save 16%?

@Sfolt, при оплате 6-ти месяцев фактически платишь за 5ть. Вроде когда есть скидки то пишут save скоко_то_денег, но т.к. писать сохрани $4 не прикольно :) написал в %-х возможно не понятно и нужно написать явно типа discount. Вообще не принципиально можно и удалить, оставить только 1 бесплатный месяц, чтобы мотивировать людей на оплату сразу нескольких месяцев, пока не получится прикрутить автоплатежи.

**Comment by blackchestnut** [comment]
Для начала хотя бы исправлю кнопку, а остальное пока не важно

**Comment by blackchestnut** [comment]
Вообще не хорошо делать не понятные тикиты
