### ISSUE TITLE
Ugly Landing :)

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#569]

**Comment by blackchestnut** [comment]
- [x] what is it? (in 5 words)
- [x] short answer - why agile season?
- [x] simple feature list
- [x] prices (private - $4 by repo, public - free forever)
- [x] link to github repo
- [ ] badge "early access"
- [x] links to privacy, security and terms

**Comment by DariaUlanova** [comment]
@blackchestnut why ugly?

**Comment by blackchestnut** [comment]
@Sfolt, срочно нужно набросать что-то, чтобы была не голая страница. На ней будет совсем все топорно и узко - она не должна тебя сбить с твоей идеи.

**Comment by DariaUlanova** [comment]
@blackchestnut ок, эти выходные наконец-то свободные, но чтобы доделать лендинг, хотела бы с тобой некоторые вопросы обсудить. У тебя будет возможность завтра или даже сегодня вечером встретиться и обсудить?

**Comment by blackchestnut** [comment]
> why ugly?

потому что буду делать я и у меня на это 180 минут :)

**Comment by blackchestnut** [comment]
@Sfolt, по поводу встречи я только за, но только вот когда получится не знаю, может завтра если только ближе к вечеру. Тебе где удобно?

**Comment by DariaUlanova** [comment]
@blackchestnut могу подойти в кафе напротив кинотеатра, где мы в прошлый раз обедали, или приходи в гости, сначала обсудим лендинг, потом мы с Пашей покажем тебе фотки из Германии, покушаем фисташек с вином).

**Comment by blackchestnut** [comment]
@Sfolt, давай я попробую вырваться к вам - с меня фисташки и бутылка вина. По времени могу лишь с ориентировать приблизительно, т.к. завтра первую часть дня буду не в туле, скорее всего после 17-00, как вам?

**Comment by DariaUlanova** [comment]
Ок, будем ждать!
