### ISSUE TITLE
Working on localhost

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#57]
http://localhost:3000/

**Comment by blackchestnut** [comment]
Add to `~/.bashrc` or `~/.zshrc`

``` shell
export GITHUB_CLIENT_ID='13e3d3ca951e22861950'
export GITHUB_CLIENT_SECRET='608657d9c2c5878ec192ae6768679196de79facc'
```

**Comment by blackchestnut** [comment]
@Sfolt попробуй у себя, у меня заработало (пробуй на `http://localhost:3000`). Только не подключай репозиторий agileseason/agileseason (какой-нибудь тестовый у себя создай на аккаунте), а то там в issues уже мои данные из локальной базы. Как будет продакшен я все почищу и уже для этого репозитория будем на agileseason.com работать.

**Comment by DariaUlanova** [comment]
@blackchestnut, не вышло, ссылка авторизации гитхаба подставила домен agileseason.dev, который у меня не работает. Если заменить домен на localhost:3000, то возникает ошибка

OmniAuth::Strategies::OAuth2::CallbackError at /auth/github/callback
redirect_uri_mismatch | The redirect_uri MUST match the registered callback URL for this application. | https://developer.github.com/v3/oauth/#redirect-uri-mismatch

**Comment by blackchestnut** [comment]
@Sfolt перегрузи консоль и запусти ее и `rails s` заново, у тебя скорее всего переменные окружения не проинициализировались. Имя приложения при запросе доступа должно быть `Agile Season (localhost)`

**Comment by DariaUlanova** [comment]
C ~/.bashrc не сработало, а с ~/.zshrc заработало.

**Comment by blackchestnut** [comment]
Хорошо. bashrc написал на случай если вдруг zshrc не стоит, забыл уточнить.
