### ISSUE TITLE
Errors on landing

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#591]

**Comment by blackchestnut** [comment]
- [x] https warning
- [x] bad url to demo (работало только если пользователь уже был создан)
- [x] broken auth (вход со 2ого раза)
- [x] jquery

**Comment by blackchestnut** [comment]
@Sfolt, посмотри пожалуйста - как у тебя будет работать. Выйти из agileseason а потом снова войти у меня если я уже в github авторизован кидает на главную и авторизует только со второго раза. У тебя так?

**Comment by blackchestnut** [comment]
Возможно это воспроизводится только входить выходить часто, т.к. браузер кэширует запрос от гитхаба

**Comment by blackchestnut** [comment]
Хотя раньше такого точно не было. По коду не могу понять что привело к такому поведению :(

**Comment by DariaUlanova** [comment]
​1.Открываю АС в разлогиненом состоянии, жму кнопку войти под аккаунтом
гитхаба, попадаю на борд АС.

2.Разлогиниваюсь, попадаю на лендинг, жму войти. Прогресс турболинков
прошел, но страница не поменялась. Жму войти повторно, меня перебросило не
на борд, а на дашборд.

3.Если р​азлогиниться, то повторяется 2 пункт.

12 августа 2015 г., 7:06 пользователь Alexander Kalinichev <
notifications@github.com> написал:

**Comment by DariaUlanova** [comment]
@blackchestnut а удобно, что с почты тоже сюда попадает)

**Comment by blackchestnut** [comment]
@Sfolt, не понял предыдущий комментарий - расскажи завтра

**Comment by DariaUlanova** [comment]
@blackchestnut ok)
