### ISSUE TITLE
Add ready to next stage/column

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#596]

**Comment by blackchestnut** [comment]
какой-то флажок нужно придумать с возможностью изменять его сразу с борда не заходя в тикет

**Comment by DariaUlanova** [comment]
@blackchestnut 
Добавлю в issue_stats колонку ready. Сохранять булево значение (готов тикет или нет) или сохранять дату, когда была нажата кнопка ready? 

Это событие, думаю, тоже нужно в логах отображать, верно?

**Comment by blackchestnut** [comment]
@Sfolt, думаю можно булевое значение, только назови его пожалуйста с `is_` вначале, чтобы было понятно что это boolean. Событие, как пожелаешь - пока не могу сказать нужно ли оно, пока не начнешь пользоваться не понятно.

**Comment by blackchestnut** [comment]
@Sfolt,
1) ready не убирается после переноса в следующую колонку
2) для этой кнопочки лучше не ждать ajax:success, а то сначала думал, что не работает - кликал несколько раз

**Comment by DariaUlanova** [comment]
@blackchestnut ты прав, сделаю.

**Comment by blackchestnut** [comment]
@Sfolt, стал тикет заметно компактнее - так лучше. Можешь совсем чуть-чуть добавить отступ от нижнего края аватарки, чтобы он соотносился слевым, а так же с верних. Визуально кажется, что аватарка съехала вниз
![uploads/2015-08-27/3218a131-76f4-441f-bd6a-b0043613e18a/Agile Season 2015-08-27 08-43-38.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-27%2F3218a131-76f4-441f-bd6a-b0043613e18a%2FAgile%20Season%202015-08-27%2008-43-38.png)

**Comment by blackchestnut** [comment]
@Sfolt, тикет перевел обратно в тест, т.к. в канбане тикеты не переносятся обратно по доске. Смысл такой, что если тикет дошел до определенной колонки, но осталась работа из других стадий - то это проблема системы. Представь конвеер где деталь уже уехала в другую часть цеха - ты не сможешь переместить ее обратно, тебе надо бежать за ней и доделывать в другой части цеха.

**Comment by DariaUlanova** [comment]
@blackchestnut ok

**Comment by blackchestnut** [comment]
Для иконки: хотя бы 3-4px
![uploads/2015-08-27/627ca379-8c72-4ee0-9826-e3fe0b2b828b/Agile Season 2015-08-27 08-52-35.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-27%2F627ca379-8c72-4ee0-9826-e3fe0b2b828b%2FAgile%20Season%202015-08-27%2008-52-35.png)

**Comment by blackchestnut** [comment]
@Sfolt, есть предложение передвинуть кнопук, т.к. ready to next stage использовать будут не все. В самый низ то же не очень хорошо, т.к. там частя снопка "закрыть", можно предпоследней - что скажешь?
![uploads/2015-08-27/42d86eb6-3dfc-4100-b296-ee0fbdc5872c/Agile Season 2015-08-27 17-37-41.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-27%2F42d86eb6-3dfc-4100-b296-ee0fbdc5872c%2FAgile%20Season%202015-08-27%2017-37-41.png)

**Comment by blackchestnut** [comment]
@Sfolt, давай еще тултип добавим для этой кнопики с полным описанием, с общим смыслом: ready to next column (или stage)

**Comment by DariaUlanova** [comment]
@blackchestnut все поправила
