### ISSUE TITLE
Need double click on button "comment" after attaching pictures to issue

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#607]

**Comment by morr** [comment]
zzz test

**Comment by morr** [comment]
@blackchestnut @Sfolt а в agileseason я не могу комментировать этот тикет!

**Comment by blackchestnut** [comment]
@morr пока отключил возможность комментировать чужой борд, но т.к. для публичных эта возможность есть в гитхабе, возможно стоит добавить для единообразия.

**Comment by DariaUlanova** [comment]
Can't attach an image by clicking 'attach images' while adding a new comment.
Drag'n'drop works.
While editing a coment it works by 'attach images'.

**Comment by Sfolt** [comment]
![uploads/2015-08-29/b69de2d7-4516-4c71-be2b-2f00282f2e75/Снимок экрана 2014-12-06 в 16.55.00.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015\-08\-29%2Fb69de2d7\-4516\-4c71\-be2b\-2f00282f2e75%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202014\-12\-06%20%D0%B2%2016\.55\.00\.png)

test

**Comment by blackchestnut** [comment]
![uploads/2015-08-29/a4252437-1c09-48fc-a85b-a7cf6dd01dc6/Agile Season 2015-08-29 10-44-31.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015\-08\-29%2Fa4252437\-1c09\-48fc\-a85b\-a7cf6dd01dc6%2FAgile%20Season%202015\-08\-29%2010\-44\-31\.png)

**Comment by DariaUlanova** [comment]
test

![uploads/2015-08-29/85f1c94b-9c4f-4af4-b82c-bf6350540175/Снимок экрана 2014-12-06 в 16.55.00.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-29%2F85f1c94b-9c4f-4af4-b82c-bf6350540175%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202014-12-06%20%D0%B2%2016.55.00.png)
