### ISSUE TITLE
Underlining renders cursive in comments. Why?

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#614]

**Comment by DariaUlanova** [comment]
![uploads/2015-08-19_ad763ee9-ff75-43bf-916c-1cb810b34ef0/Снимок экрана 2015-08-19 в 20.00.56.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-19_ad763ee9-ff75-43bf-916c-1cb810b34ef0%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-08-19%20%D0%B2%2020.00.56.png)
![uploads/2015-08-19_ad763ee9-ff75-43bf-916c-1cb810b34ef0/Снимок экрана 2015-08-19 в 20.01.10.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-19_ad763ee9-ff75-43bf-916c-1cb810b34ef0%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-08-19%20%D0%B2%2020.01.10.png)

**Comment by blackchestnut** [comment]
@Sfolt, прикольно, не обратил сразу внимание. пробовал удалять часть кода - просто внизапно появляется. Оставлю ссылку на тикет на память #558

**Comment by blackchestnut** [comment]
@Sfolt, из-за "_" - нужно оборачивать ``, думаю можно не фиксить и даже не тратить пока время в настройках, т.к. код без ковычек достаточно редкое явление.
