### ISSUE TITLE
Update to Ruby 2.2.2 (2.2.3)

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#625]

**Comment by morr** [comment]
@blackchestnut 2.2.3  :+1:

**Comment by blackchestnut** [comment]
- [x] ruby + chef
- [x] rails 4.2.4
- [x] gems

**Comment by blackchestnut** [comment]
Bugs
- [x] From issues#show: move to "Done" -> close => issue disappered

**Comment by blackchestnut** [comment]
@Sfolt, обновил, но без накладок не обошлось - не был доступен сервис несколько минут :(

**Comment by DariaUlanova** [comment]
@blackchestnut в кодшипе не нужно разве заменить версию руби?

**Comment by blackchestnut** [comment]
@Sfolt поправил, влияло только на тесты, но возможно из-за этого падали билды с ошибкой `system`
