### ISSUE TITLE
Remove cursor pointer from issue.title:hover on board

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#632]

**Comment by DariaUlanova** [comment]
@blackchestnut, are you sure? The issue title is a link to the issue page.

**Comment by blackchestnut** [comment]
@Sfolt, да ты права без него не заметно и не понятно тогда как вначале попасть на issues#show.
Тикет создал, т.к. начал себя ловить на мысли, что раньше перетаскивал тикет там где сейчас появилась кнопка ready. Интуитивно начал переносить курсор в другое место и это другое место стало текст, а там другой курсор :)
В общем нужно оставить как есть, т.к. так правильнее.
