### ISSUE TITLE
Add option to allow public read-only access to private boards

### ISSUE THREAD

**Issue by morr** [agileseason/agileseason-v1#634]
Please :)

**Comment by blackchestnut** [comment]
- [x] Модифицировать кэш для раздельной работы у пользователей с правами и без них
- [x] Labels
- [x] Collaborators
- [x] Issues
- [x] Заглушку для readonly пользователей если по каким-то причинам в кэше данных все таки не оказалось для борда (если поставщик данных совсем забросил борд либо внезапно очистился кэш).
- [x] Разрешить изменять видимость для приватных репозиториев.
- [x] Проверить поведение при внезапном закрытии форда.
- [x] #750
- [x] news in twitter

Дополнительные проверки (продакшен)
- [x] вебхуки
- [x] закрите борда

Errors
- [x] #749

**Comment by blackchestnut** [comment]
@morr
you're welcome, can try.

**Comment by blackchestnut** [comment]
Change in settings
![uploads/2015-11-15/59f7ab6b-f444-45e1-b932-befe88941508/Agile Season 2015-11-15 21-03-10.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-11-15%2F59f7ab6b-f444-45e1-b932-befe88941508%2FAgile%20Season%202015-11-15%2021-03-10.png)
