### ISSUE TITLE
Let's remove the repos which are not allowed for creating AS board from the repo list

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#638]

**Comment by DariaUlanova** [comment]
@blackchestnut

![uploads/2015-08-29/4a54069f-549a-4864-87c0-9de14db25f33/Снимок экрана 2015-08-29 в 8.55.17.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-29%2F4a54069f-549a-4864-87c0-9de14db25f33%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-08-29%20%D0%B2%208.55.17.png)

**Comment by blackchestnut** [comment]
@Sfolt, можно, изначально оставил для того, чтобы можно было как-то понять почему части репозиториев нет в списке. Возможно это лишнее.

**Comment by blackchestnut** [comment]
@Sfolt, давай убирем, только нужно будет отдельно посмотреть, что эти репозитории появляются обратно в списке с кнопкой Go to Board, если кто-то другой создал репозиторий (у кого есть права).

**Comment by DariaUlanova** [comment]
@blackchestnut, ok #642
