### ISSUE TITLE
Let's move the button 'Append a new column' to the settings page. It is rare to use and it is one of the board setting

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#639]

**Comment by DariaUlanova** [comment]
And it's breaking

![uploads/2015-08-29/28d0d472-2131-447b-9f5f-ab23bd1915b4/Снимок экрана 2015-08-29 в 9.07.08.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-08-29%2F28d0d472-2131-447b-9f5f-ab23bd1915b4%2F%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-08-29%20%D0%B2%209.07.08.png)

**Comment by blackchestnut** [comment]
@Sfolt,
agree

**Comment by blackchestnut** [comment]
Add #640
