### ISSUE TITLE
Check access to repo for multiple users

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#64]

**Comment by blackchestnut** [comment]
@Sfolt теперь у тебя в списке http://agileseason.com/repos должна быть ссылка с доступом к доске agileseason/agileseason, посмотри так же пожалуйста можешь ли ты двигать тикеты между колонками?

**Comment by DariaUlanova** [comment]
Ссылки к agileseason/agileseason нет. В место неё Not enough permissions.

Тикеты между колонками двигаются.

**Comment by blackchestnut** [comment]
То что ссылки нет - это странно, возможно у меня что-то напутано либо в коде, либо в настройках репозиртория. Как-то нужно придумать подебажить... хм.

**Comment by blackchestnut** [comment]
@Sfolt как будет возможность закоммить что-нибудь сразу в мастер или подмержуй какую-нибудь законченную часть, чтобы отмести предположение о том, что недостаточно прав в настройках для репозитория.

**Comment by DariaUlanova** [comment]
@blackchestnut, не поняла. Как то, что я замерджу мои последние правки (верстка в основном) помогут выявить недостаток прав?

**Comment by blackchestnut** [comment]
Я тестировал совместный доступ пользователя к board-у, который не создавал репозиторий, в варианте без команд и организаций (в случае с организацией в гитхабе немного подругому права раздаются). Коммитом хотел просто удостовериться, что у тебя прав хватает, чтобы вносить изменения в основную ветку. В идеале здорово, конечно, у тебя подебажить метод `GithubApi::Repos#repos` чтобы понять что там лежит в repo.permissions. Ошибка у меня скорее всего в методе `RepoPresenter#board_control?` на строчке permissions.admin. Если будет возможность посмотри, что у тебя в хеше permissions для репозитория `agileseason/agileseason` лежит.

**Comment by DariaUlanova** [comment]
Ок, посмотрю.

**Comment by blackchestnut** [comment]
@Sfolt хотя подожди пожалуйста, а у тебя надпись `Not enough permissions` локльно или на `http://agileseason.com/`?

**Comment by DariaUlanova** [comment]
Локально, сорри, на agileseason.com ссылка есть.

**Comment by blackchestnut** [comment]
@Sfolt ок, тогда все хорошо, так и должно быть.
