### ISSUE TITLE
Often I want to leave my comment under a certain comment. Let's do this feature

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#665]

**Comment by blackchestnut** [comment]
@Sfolt, you mean - to create comment with quote. right?

**Comment by DariaUlanova** [comment]
@blackchestnut
Instead to make one comment with quotes referencing to many not mine comments I want to make many subcomments hierarchically

**Comment by blackchestnut** [comment]
@Sfolt, good idea we can save hierachy by comments ids in our database.

**Comment by DariaUlanova** [comment]
#668
