### ISSUE TITLE
User can see the comments he haven't read yet

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#669]

**Comment by blackchestnut** [comment]
Но показывать это нужно только для тех у кого есть права на борд, т.к. если борд публичный и я зашел туда только посмотреть, то отмечать просмотренные не нужно чтобы базу не засорять.

**Comment by blackchestnut** [comment]
Можно использовать самый простой способ сохранить на разумное время (месяц например) в "редисе" последний прочтенный комментарий для пользователя по ключу `[user_id, board_id, issue_number] => last_comment_id`. А при просмотре подсвечивать все комментарии (вопрос как), у которых `id > last_comment_id`. Не подсвечивать свои комментарии.

**Comment by blackchestnut** [comment]
Хорошо бы придумать для "гостей" вариант хранения в куках с небольшим временем жизни. Но эта поведение в фиче совсем не обязательно - если надоест делать, то на не авторизованных можно забить.
