### ISSUE TITLE
Broken buttons on boards#new

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#672]

**Comment by blackchestnut** [comment]
![uploads/2015-09-06/4a3bceb2-9ed6-484a-9ee3-f9762e5bd593/Agile Season 2015-09-06 18-33-50.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-09-06%2F4a3bceb2-9ed6-484a-9ee3-f9762e5bd593%2FAgile%20Season%202015-09-06%2018-33-50.png)

**Comment by DariaUlanova** [comment]
@blackchestnut Ооого как давно у меня такой психоделии не выходило

**Comment by blackchestnut** [comment]
@Sfolt похоже это просто стили у меня не сразу обновились
