### ISSUE TITLE
Return the column settings on the board

### ISSUE THREAD

**Issue by DariaUlanova** [agileseason/agileseason-v1#679]

**Comment by blackchestnut** [comment]
@Sfolt а что в этом реквесте осталось зделать кроме переноса файликов?

**Comment by blackchestnut** [comment]
Делаю ребейз и пушу с форсом, нужно если потребуется ветка, то нужно сначала извлечься

**Comment by blackchestnut** [comment]
@Sfolt, попробовал, поюзал - из попапов настройки все таки так удобнее оказались. При встрече как-нибудь расскажи про класс `@View`
