### ISSUE TITLE
generate changelog with issues in last column

### ISSUE THREAD

**Issue by morr** [agileseason/agileseason-v1#698]
![monosnap 2015-09-24 01-42-57](https://cloud.githubusercontent.com/assets/134610/10061020/1928e98c-625e-11e5-8044-d0d6103fa975.png)

**Comment by blackchestnut** [comment]
@morr почему только в последней?

**Comment by morr** [comment]
@blackchestnut последняя колонка = сделано. нет? можно и в любую другую, может быть, если в настройках колонки галочка стоит?

**Comment by blackchestnut** [comment]
@morr мне сейчас видится, что это может быть пункт в меню для любой колонки, т.к. после done может быть еще у кого-то много колонок. Как вариант может быть нужно если хочется вытащить то что будет сделано, например из backlog-a или todo, но это уже фантазии.

waiting #679

**Comment by blackchestnut** [comment]
Если задача закрыта, то [x] - ..., иначе [ ] - ...

**Comment by blackchestnut** [comment]
За прошлую неделю 2а раза было нужно быстро получить список тикетов и вот сегодня опять. Добавлю пока маленькую ссылку на последней колонке. Будет открываться в новом окне простой текст в стиле гитхабовских чеклистов.
