### ISSUE TITLE
Issue:hover doesn't work in safari

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#751]

**Comment by blackchestnut** [comment]
@Sfolt
have you a same problem?

**Comment by blackchestnut** [comment]
Дело было не в warning-ах

**Comment by blackchestnut** [comment]
Попробовать удалить css от jquery-ui/themes

**Comment by DariaUlanova** [comment]
@blackchestnut Смотрю в сафари, стили по ховеру работают, в чем проблема?

**Comment by blackchestnut** [comment]
@Sfolt хм, не понятно. У меня почему-то не работают. Причем никакие не на одной странице. Даже ссылки обычные не меняют стиль курсора и сами не изменяются. Мистика, причем в develop локально все ОК :(

**Comment by blackchestnut** [comment]
@Sfolt после 3-й перезагрузки safari все заработало... видимо какой-то баг был.
