### ISSUE TITLE
Show comments in Issue#show

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#80]

**Comment by blackchestnut** [comment]
@Sfolt влил код, здорово получилось! Есть 2а коммента в https://github.com/agileseason/agileseason/pull/98, если получится можешь закоммитить в мастер сразу.

**Comment by blackchestnut** [comment]
@Sfolt еще один момент, такое ощущение, что у тебя дома на локальной машине в конфиге git-а настроена не тот email, либо не тот username:
![sfolt daria 2015-01-20 06-41-27](https://cloud.githubusercontent.com/assets/2400100/5811921/9548d470-a06f-11e4-94f5-899b8523081c.png)
![agileseason 2015-01-20 06-44-50](https://cloud.githubusercontent.com/assets/2400100/5811935/e31d8146-a06f-11e4-8e99-f27d08669902.png)
Из-за чего гитхаб считает 2мя людьми. Инвайт видимо ушел на darya.office@gmail.com, то что у тебя было на тот момент в аккаунте гитхаба - смаое простое это локально попробуй у себя сделать почту darya.office@gmail.com в настройках гита.

**Comment by DariaUlanova** [comment]
Объявила у себя в гите имя и имеил, вроде первоначальные имя и аватарка появились при коммите.
