### ISSUE TITLE
Add methods for milestones

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#9]

**Comment by blackchestnut** [comment]
@Sfolt если хочешь можешь попробовать сделать. Про итерации немного тут написано https://en.wikipedia.org/wiki/Scrum_(software_development) в разделе "Sprint".

**Comment by DariaUlanova** [comment]
Ок, могу заняться этой задачей после верстки.

**Comment by DariaUlanova** [comment]
@blackchestnut, правильно ли я понимаю задачу?

Через АПИ сделать возможность создать milestone (итерацию) и получать такие от гитхаба. Для итерации назначается дата. В итерацию добавляются тикеты. Где-то ещё должен быть прогресс бар этой итерации. Что ещё имелось в виду?

В AS можно добавить скрам-борд. Что ты хотел сделать на скрам-борде?

**Comment by blackchestnut** [comment]
@Sfolt 

> Через АПИ сделать возможность создать milestone (итерацию) и получать такие от гитхаба.

Да, пока не знаю нужно ли их как-то отмечать отдельно именем по аналогии с ярлыками в колонках. В скрам итерации идут 1-2 недели и их много получается и не запариваются с их названием обычно это Sprint 1, Sprint 2 и т.д. Длинну итерации нужно выбрать заранее - это настройка борда. Эти настройки будут сильно отличаться между Scrum и Kanban, так что предлагаю сделать отдельную табличку типа ScrumSettings для складирования настроек правда тогда придется делать 2а поля board.scrum_settings_id, board.kanban_settings_id. Можно еще в борд положить хэш, который будет свой в зависимости от типа, как думаешь может что лучше?

> В итерацию добавляются тикеты.

Да и это то же переодическая задача в момент создания новой итерации.

> Где-то ещё должен быть прогресс бар этой итерации.

Это не в этой задаче, но возможно быстрая инфа о проценте завершенных будет не лишней (ее возможно то же можно получить от github). В scrum как правило эту задачу решает график Burndown Chart, добавил несколько ссылок в комменте  к https://github.com/agileseason/agileseason/issues/90

> В AS можно добавить скрам-борд. Что ты хотел сделать на скрам-борде?

По факту там тот же борд, возможно только с возможностью переключения между итерациями, т.к. в скраме планирование осуществляется через них - как будто спринт это новая доска.

**Comment by blackchestnut** [comment]
@Sfolt предварительный бэкэнд и структуру бд для настроек сделаю в #69

**Comment by blackchestnut** [comment]
Moved to the next mvp.
